// automatically generated by the FlatBuffers compiler, do not modify

using System;
using FlatBuffers;

public sealed class EnterRoomToC_Data : Table {
  public static EnterRoomToC_Data GetRootAsEnterRoomToC_Data(ByteBuffer _bb) { return GetRootAsEnterRoomToC_Data(_bb, new EnterRoomToC_Data()); }
  public static EnterRoomToC_Data GetRootAsEnterRoomToC_Data(ByteBuffer _bb, EnterRoomToC_Data obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public EnterRoomToC_Data __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public int Result { get { int o = __offset(4); return o != 0 ? bb.GetInt(o + bb_pos) : (int)0; } }
  public int PlayerIndex { get { int o = __offset(6); return o != 0 ? bb.GetInt(o + bb_pos) : (int)0; } }
  public int GetPlayersMapKey(int j) { int o = __offset(8); return o != 0 ? bb.GetInt(__vector(o) + j * 4) : (int)0; }
  public int PlayersMapKeyLength { get { int o = __offset(8); return o != 0 ? __vector_len(o) : 0; } }
  public ArraySegment<byte>? GetPlayersMapKeyBytes() { return __vector_as_arraysegment(8); }
  public string GetPlayersMapValue(int j) { int o = __offset(10); return o != 0 ? __string(__vector(o) + j * 4) : null; }
  public int PlayersMapValueLength { get { int o = __offset(10); return o != 0 ? __vector_len(o) : 0; } }

  public static Offset<EnterRoomToC_Data> CreateEnterRoomToC_Data(FlatBufferBuilder builder,
      int Result = 0,
      int PlayerIndex = 0,
      VectorOffset PlayersMapKeyOffset = default(VectorOffset),
      VectorOffset PlayersMapValueOffset = default(VectorOffset)) {
    builder.StartObject(4);
    EnterRoomToC_Data.AddPlayersMapValue(builder, PlayersMapValueOffset);
    EnterRoomToC_Data.AddPlayersMapKey(builder, PlayersMapKeyOffset);
    EnterRoomToC_Data.AddPlayerIndex(builder, PlayerIndex);
    EnterRoomToC_Data.AddResult(builder, Result);
    return EnterRoomToC_Data.EndEnterRoomToC_Data(builder);
  }

  public static void StartEnterRoomToC_Data(FlatBufferBuilder builder) { builder.StartObject(4); }
  public static void AddResult(FlatBufferBuilder builder, int Result) { builder.AddInt(0, Result, 0); }
  public static void AddPlayerIndex(FlatBufferBuilder builder, int PlayerIndex) { builder.AddInt(1, PlayerIndex, 0); }
  public static void AddPlayersMapKey(FlatBufferBuilder builder, VectorOffset PlayersMapKeyOffset) { builder.AddOffset(2, PlayersMapKeyOffset.Value, 0); }
  public static VectorOffset CreatePlayersMapKeyVector(FlatBufferBuilder builder, int[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddInt(data[i]); return builder.EndVector(); }
  public static void StartPlayersMapKeyVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddPlayersMapValue(FlatBufferBuilder builder, VectorOffset PlayersMapValueOffset) { builder.AddOffset(3, PlayersMapValueOffset.Value, 0); }
  public static VectorOffset CreatePlayersMapValueVector(FlatBufferBuilder builder, StringOffset[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static void StartPlayersMapValueVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<EnterRoomToC_Data> EndEnterRoomToC_Data(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<EnterRoomToC_Data>(o);
  }
};

