// automatically generated by the FlatBuffers compiler, do not modify

using System;
using FlatBuffers;

public sealed class GameEventStopToR_Data : Table {
  public static GameEventStopToR_Data GetRootAsGameEventStopToR_Data(ByteBuffer _bb) { return GetRootAsGameEventStopToR_Data(_bb, new GameEventStopToR_Data()); }
  public static GameEventStopToR_Data GetRootAsGameEventStopToR_Data(ByteBuffer _bb, GameEventStopToR_Data obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public GameEventStopToR_Data __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public int PlayerIndex { get { int o = __offset(4); return o != 0 ? bb.GetInt(o + bb_pos) : (int)0; } }
  public FBSData.Vector3 Pos { get { return GetPos(new FBSData.Vector3()); } }
  public FBSData.Vector3 GetPos(FBSData.Vector3 obj) { int o = __offset(6); return o != 0 ? obj.__init(o + bb_pos, bb) : null; }

  public static void StartGameEventStopToR_Data(FlatBufferBuilder builder) { builder.StartObject(2); }
  public static void AddPlayerIndex(FlatBufferBuilder builder, int PlayerIndex) { builder.AddInt(0, PlayerIndex, 0); }
  public static void AddPos(FlatBufferBuilder builder, Offset<FBSData.Vector3> PosOffset) { builder.AddStruct(1, PosOffset.Value, 0); }
  public static Offset<GameEventStopToR_Data> EndGameEventStopToR_Data(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<GameEventStopToR_Data>(o);
  }
};

