// automatically generated by the FlatBuffers compiler, do not modify

using System;
using FlatBuffers;

public sealed class GameEvent_BehaviorEnd : Table {
  public static GameEvent_BehaviorEnd GetRootAsGameEvent_BehaviorEnd(ByteBuffer _bb) { return GetRootAsGameEvent_BehaviorEnd(_bb, new GameEvent_BehaviorEnd()); }
  public static GameEvent_BehaviorEnd GetRootAsGameEvent_BehaviorEnd(ByteBuffer _bb, GameEvent_BehaviorEnd obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public GameEvent_BehaviorEnd __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public int EntityID { get { int o = __offset(4); return o != 0 ? bb.GetInt(o + bb_pos) : (int)0; } }
  public float EndTime { get { int o = __offset(6); return o != 0 ? bb.GetFloat(o + bb_pos) : (float)0.0f; } }
  public int BehaviorID { get { int o = __offset(8); return o != 0 ? bb.GetInt(o + bb_pos) : (int)0; } }

  public static Offset<GameEvent_BehaviorEnd> CreateGameEvent_BehaviorEnd(FlatBufferBuilder builder,
      int EntityID = 0,
      float EndTime = 0.0f,
      int BehaviorID = 0) {
    builder.StartObject(3);
    GameEvent_BehaviorEnd.AddBehaviorID(builder, BehaviorID);
    GameEvent_BehaviorEnd.AddEndTime(builder, EndTime);
    GameEvent_BehaviorEnd.AddEntityID(builder, EntityID);
    return GameEvent_BehaviorEnd.EndGameEvent_BehaviorEnd(builder);
  }

  public static void StartGameEvent_BehaviorEnd(FlatBufferBuilder builder) { builder.StartObject(3); }
  public static void AddEntityID(FlatBufferBuilder builder, int EntityID) { builder.AddInt(0, EntityID, 0); }
  public static void AddEndTime(FlatBufferBuilder builder, float EndTime) { builder.AddFloat(1, EndTime, 0.0f); }
  public static void AddBehaviorID(FlatBufferBuilder builder, int BehaviorID) { builder.AddInt(2, BehaviorID, 0); }
  public static Offset<GameEvent_BehaviorEnd> EndGameEvent_BehaviorEnd(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<GameEvent_BehaviorEnd>(o);
  }
};

