// automatically generated by the FlatBuffers compiler, do not modify

using System;
using FlatBuffers;

public sealed class GameEvent_StateEnd : Table {
  public static GameEvent_StateEnd GetRootAsGameEvent_StateEnd(ByteBuffer _bb) { return GetRootAsGameEvent_StateEnd(_bb, new GameEvent_StateEnd()); }
  public static GameEvent_StateEnd GetRootAsGameEvent_StateEnd(ByteBuffer _bb, GameEvent_StateEnd obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public GameEvent_StateEnd __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public int EntityID { get { int o = __offset(4); return o != 0 ? bb.GetInt(o + bb_pos) : (int)0; } }
  public float EndTime { get { int o = __offset(6); return o != 0 ? bb.GetFloat(o + bb_pos) : (float)0.0f; } }
  public int StateID { get { int o = __offset(8); return o != 0 ? bb.GetInt(o + bb_pos) : (int)0; } }

  public static Offset<GameEvent_StateEnd> CreateGameEvent_StateEnd(FlatBufferBuilder builder,
      int EntityID = 0,
      float EndTime = 0.0f,
      int StateID = 0) {
    builder.StartObject(3);
    GameEvent_StateEnd.AddStateID(builder, StateID);
    GameEvent_StateEnd.AddEndTime(builder, EndTime);
    GameEvent_StateEnd.AddEntityID(builder, EntityID);
    return GameEvent_StateEnd.EndGameEvent_StateEnd(builder);
  }

  public static void StartGameEvent_StateEnd(FlatBufferBuilder builder) { builder.StartObject(3); }
  public static void AddEntityID(FlatBufferBuilder builder, int EntityID) { builder.AddInt(0, EntityID, 0); }
  public static void AddEndTime(FlatBufferBuilder builder, float EndTime) { builder.AddFloat(1, EndTime, 0.0f); }
  public static void AddStateID(FlatBufferBuilder builder, int StateID) { builder.AddInt(2, StateID, 0); }
  public static Offset<GameEvent_StateEnd> EndGameEvent_StateEnd(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<GameEvent_StateEnd>(o);
  }
};

