// automatically generated by the FlatBuffers compiler, do not modify

using System;
using FlatBuffers;

public sealed class GameEvent_BehaviorStart : Table {
  public static GameEvent_BehaviorStart GetRootAsGameEvent_BehaviorStart(ByteBuffer _bb) { return GetRootAsGameEvent_BehaviorStart(_bb, new GameEvent_BehaviorStart()); }
  public static GameEvent_BehaviorStart GetRootAsGameEvent_BehaviorStart(ByteBuffer _bb, GameEvent_BehaviorStart obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public GameEvent_BehaviorStart __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public int EntityID { get { int o = __offset(4); return o != 0 ? bb.GetInt(o + bb_pos) : (int)0; } }
  public float StartTime { get { int o = __offset(6); return o != 0 ? bb.GetFloat(o + bb_pos) : (float)0.0f; } }
  public int BehaviorID { get { int o = __offset(8); return o != 0 ? bb.GetInt(o + bb_pos) : (int)0; } }

  public static Offset<GameEvent_BehaviorStart> CreateGameEvent_BehaviorStart(FlatBufferBuilder builder,
      int EntityID = 0,
      float StartTime = 0.0f,
      int BehaviorID = 0) {
    builder.StartObject(3);
    GameEvent_BehaviorStart.AddBehaviorID(builder, BehaviorID);
    GameEvent_BehaviorStart.AddStartTime(builder, StartTime);
    GameEvent_BehaviorStart.AddEntityID(builder, EntityID);
    return GameEvent_BehaviorStart.EndGameEvent_BehaviorStart(builder);
  }

  public static void StartGameEvent_BehaviorStart(FlatBufferBuilder builder) { builder.StartObject(3); }
  public static void AddEntityID(FlatBufferBuilder builder, int EntityID) { builder.AddInt(0, EntityID, 0); }
  public static void AddStartTime(FlatBufferBuilder builder, float StartTime) { builder.AddFloat(1, StartTime, 0.0f); }
  public static void AddBehaviorID(FlatBufferBuilder builder, int BehaviorID) { builder.AddInt(2, BehaviorID, 0); }
  public static Offset<GameEvent_BehaviorStart> EndGameEvent_BehaviorStart(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<GameEvent_BehaviorStart>(o);
  }
};

