// automatically generated by the FlatBuffers compiler, do not modify

public enum GameEventType : sbyte
{
 BehaviorStart = 0,
 BehaviorEnd = 1,
 StateStart = 2,
 StateEnd = 3,
 Transform = 4,
 Collision = 5,
};

