// automatically generated by the FlatBuffers compiler, do not modify

using System;
using FlatBuffers;

public sealed class GameEvent_Position : Table {
  public static GameEvent_Position GetRootAsGameEvent_Position(ByteBuffer _bb) { return GetRootAsGameEvent_Position(_bb, new GameEvent_Position()); }
  public static GameEvent_Position GetRootAsGameEvent_Position(ByteBuffer _bb, GameEvent_Position obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public GameEvent_Position __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public int EntityID { get { int o = __offset(4); return o != 0 ? bb.GetInt(o + bb_pos) : (int)0; } }
  public float StartTime { get { int o = __offset(6); return o != 0 ? bb.GetFloat(o + bb_pos) : (float)0.0f; } }
  public float EndTime { get { int o = __offset(8); return o != 0 ? bb.GetFloat(o + bb_pos) : (float)0.0f; } }
  public FBSData.Vector3 StartPosition { get { return GetStartPosition(new FBSData.Vector3()); } }
  public FBSData.Vector3 GetStartPosition(FBSData.Vector3 obj) { int o = __offset(10); return o != 0 ? obj.__init(o + bb_pos, bb) : null; }
  public FBSData.Vector3 EndPosition { get { return GetEndPosition(new FBSData.Vector3()); } }
  public FBSData.Vector3 GetEndPosition(FBSData.Vector3 obj) { int o = __offset(12); return o != 0 ? obj.__init(o + bb_pos, bb) : null; }

  public static void StartGameEvent_Position(FlatBufferBuilder builder) { builder.StartObject(5); }
  public static void AddEntityID(FlatBufferBuilder builder, int EntityID) { builder.AddInt(0, EntityID, 0); }
  public static void AddStartTime(FlatBufferBuilder builder, float StartTime) { builder.AddFloat(1, StartTime, 0.0f); }
  public static void AddEndTime(FlatBufferBuilder builder, float EndTime) { builder.AddFloat(2, EndTime, 0.0f); }
  public static void AddStartPosition(FlatBufferBuilder builder, Offset<FBSData.Vector3> StartPositionOffset) { builder.AddStruct(3, StartPositionOffset.Value, 0); }
  public static void AddEndPosition(FlatBufferBuilder builder, Offset<FBSData.Vector3> EndPositionOffset) { builder.AddStruct(4, EndPositionOffset.Value, 0); }
  public static Offset<GameEvent_Position> EndGameEvent_Position(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<GameEvent_Position>(o);
  }
};

