// automatically generated by the FlatBuffers compiler, do not modify

using System;
using FlatBuffers;

public sealed class GameEvent_Rotation : Table {
  public static GameEvent_Rotation GetRootAsGameEvent_Rotation(ByteBuffer _bb) { return GetRootAsGameEvent_Rotation(_bb, new GameEvent_Rotation()); }
  public static GameEvent_Rotation GetRootAsGameEvent_Rotation(ByteBuffer _bb, GameEvent_Rotation obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public GameEvent_Rotation __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public int EntityID { get { int o = __offset(4); return o != 0 ? bb.GetInt(o + bb_pos) : (int)0; } }
  public float StartTime { get { int o = __offset(6); return o != 0 ? bb.GetFloat(o + bb_pos) : (float)0.0f; } }
  public float EndTime { get { int o = __offset(8); return o != 0 ? bb.GetFloat(o + bb_pos) : (float)0.0f; } }
  public FBSData.Vector3 StartRotation { get { return GetStartRotation(new FBSData.Vector3()); } }
  public FBSData.Vector3 GetStartRotation(FBSData.Vector3 obj) { int o = __offset(10); return o != 0 ? obj.__init(o + bb_pos, bb) : null; }
  public FBSData.Vector3 EndRotation { get { return GetEndRotation(new FBSData.Vector3()); } }
  public FBSData.Vector3 GetEndRotation(FBSData.Vector3 obj) { int o = __offset(12); return o != 0 ? obj.__init(o + bb_pos, bb) : null; }

  public static void StartGameEvent_Rotation(FlatBufferBuilder builder) { builder.StartObject(5); }
  public static void AddEntityID(FlatBufferBuilder builder, int EntityID) { builder.AddInt(0, EntityID, 0); }
  public static void AddStartTime(FlatBufferBuilder builder, float StartTime) { builder.AddFloat(1, StartTime, 0.0f); }
  public static void AddEndTime(FlatBufferBuilder builder, float EndTime) { builder.AddFloat(2, EndTime, 0.0f); }
  public static void AddStartRotation(FlatBufferBuilder builder, Offset<FBSData.Vector3> StartRotationOffset) { builder.AddStruct(3, StartRotationOffset.Value, 0); }
  public static void AddEndRotation(FlatBufferBuilder builder, Offset<FBSData.Vector3> EndRotationOffset) { builder.AddStruct(4, EndRotationOffset.Value, 0); }
  public static Offset<GameEvent_Rotation> EndGameEvent_Rotation(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<GameEvent_Rotation>(o);
  }
};

