// automatically generated by the FlatBuffers compiler, do not modify

using System;
using FlatBuffers;

public sealed class GameStartToC_Data : Table {
  public static GameStartToC_Data GetRootAsGameStartToC_Data(ByteBuffer _bb) { return GetRootAsGameStartToC_Data(_bb, new GameStartToC_Data()); }
  public static GameStartToC_Data GetRootAsGameStartToC_Data(ByteBuffer _bb, GameStartToC_Data obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public GameStartToC_Data __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }


  public static void StartGameStartToC_Data(FlatBufferBuilder builder) { builder.StartObject(0); }
  public static Offset<GameStartToC_Data> EndGameStartToC_Data(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<GameStartToC_Data>(o);
  }
};

