// automatically generated by the FlatBuffers compiler, do not modify

using System;
using FlatBuffers;

public sealed class SelectNormalGameToC_Data : Table {
  public static SelectNormalGameToC_Data GetRootAsSelectNormalGameToC_Data(ByteBuffer _bb) { return GetRootAsSelectNormalGameToC_Data(_bb, new SelectNormalGameToC_Data()); }
  public static SelectNormalGameToC_Data GetRootAsSelectNormalGameToC_Data(ByteBuffer _bb, SelectNormalGameToC_Data obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public SelectNormalGameToC_Data __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public int Result { get { int o = __offset(4); return o != 0 ? bb.GetInt(o + bb_pos) : (int)0; } }
  public int ExpectedTime { get { int o = __offset(6); return o != 0 ? bb.GetInt(o + bb_pos) : (int)0; } }

  public static Offset<SelectNormalGameToC_Data> CreateSelectNormalGameToC_Data(FlatBufferBuilder builder,
      int Result = 0,
      int ExpectedTime = 0) {
    builder.StartObject(2);
    SelectNormalGameToC_Data.AddExpectedTime(builder, ExpectedTime);
    SelectNormalGameToC_Data.AddResult(builder, Result);
    return SelectNormalGameToC_Data.EndSelectNormalGameToC_Data(builder);
  }

  public static void StartSelectNormalGameToC_Data(FlatBufferBuilder builder) { builder.StartObject(2); }
  public static void AddResult(FlatBufferBuilder builder, int Result) { builder.AddInt(0, Result, 0); }
  public static void AddExpectedTime(FlatBufferBuilder builder, int ExpectedTime) { builder.AddInt(1, ExpectedTime, 0); }
  public static Offset<SelectNormalGameToC_Data> EndSelectNormalGameToC_Data(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<SelectNormalGameToC_Data>(o);
  }
};

