// automatically generated by the FlatBuffers compiler, do not modify

#ifndef FLATBUFFERS_GENERATED_CREATEROOMTOR_FBS_H_
#define FLATBUFFERS_GENERATED_CREATEROOMTOR_FBS_H_

#include "flatbuffers/flatbuffers.h"

namespace FBS {

struct CreateRoomToR;

struct CreateRoomToR FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_MATCHID = 4,
    VT_PLAYERS = 6
  };
  int32_t MatchID() const { return GetField<int32_t>(VT_MATCHID, 0); }
  const flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>> *Players() const { return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>> *>(VT_PLAYERS); }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_MATCHID) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, VT_PLAYERS) &&
           verifier.Verify(Players()) &&
           verifier.VerifyVectorOfStrings(Players()) &&
           verifier.EndTable();
  }
};

struct CreateRoomToRBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_MatchID(int32_t MatchID) { fbb_.AddElement<int32_t>(CreateRoomToR::VT_MATCHID, MatchID, 0); }
  void add_Players(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>>> Players) { fbb_.AddOffset(CreateRoomToR::VT_PLAYERS, Players); }
  CreateRoomToRBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  CreateRoomToRBuilder &operator=(const CreateRoomToRBuilder &);
  flatbuffers::Offset<CreateRoomToR> Finish() {
    auto o = flatbuffers::Offset<CreateRoomToR>(fbb_.EndTable(start_, 2));
    return o;
  }
};

inline flatbuffers::Offset<CreateRoomToR> CreateCreateRoomToR(flatbuffers::FlatBufferBuilder &_fbb,
    int32_t MatchID = 0,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>>> Players = 0) {
  CreateRoomToRBuilder builder_(_fbb);
  builder_.add_Players(Players);
  builder_.add_MatchID(MatchID);
  return builder_.Finish();
}

inline flatbuffers::Offset<CreateRoomToR> CreateCreateRoomToRDirect(flatbuffers::FlatBufferBuilder &_fbb,
    int32_t MatchID = 0,
    const std::vector<flatbuffers::Offset<flatbuffers::String>> *Players = nullptr) {
  return CreateCreateRoomToR(_fbb, MatchID, Players ? _fbb.CreateVector<flatbuffers::Offset<flatbuffers::String>>(*Players) : 0);
}

}  // namespace FBS

#endif  // FLATBUFFERS_GENERATED_CREATEROOMTOR_FBS_H_
