// automatically generated by the FlatBuffers compiler, do not modify

#ifndef FLATBUFFERS_GENERATED_CREATEROOMTOL_FBS_H_
#define FLATBUFFERS_GENERATED_CREATEROOMTOL_FBS_H_

#include "flatbuffers/flatbuffers.h"

namespace FBS {

struct CreateRoomToL;

struct CreateRoomToL FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_RESULT = 4,
    VT_PLAYERS = 6
  };
  int32_t Result() const { return GetField<int32_t>(VT_RESULT, 0); }
  const flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>> *Players() const { return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>> *>(VT_PLAYERS); }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_RESULT) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, VT_PLAYERS) &&
           verifier.Verify(Players()) &&
           verifier.VerifyVectorOfStrings(Players()) &&
           verifier.EndTable();
  }
};

struct CreateRoomToLBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_Result(int32_t Result) { fbb_.AddElement<int32_t>(CreateRoomToL::VT_RESULT, Result, 0); }
  void add_Players(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>>> Players) { fbb_.AddOffset(CreateRoomToL::VT_PLAYERS, Players); }
  CreateRoomToLBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  CreateRoomToLBuilder &operator=(const CreateRoomToLBuilder &);
  flatbuffers::Offset<CreateRoomToL> Finish() {
    auto o = flatbuffers::Offset<CreateRoomToL>(fbb_.EndTable(start_, 2));
    return o;
  }
};

inline flatbuffers::Offset<CreateRoomToL> CreateCreateRoomToL(flatbuffers::FlatBufferBuilder &_fbb,
    int32_t Result = 0,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>>> Players = 0) {
  CreateRoomToLBuilder builder_(_fbb);
  builder_.add_Players(Players);
  builder_.add_Result(Result);
  return builder_.Finish();
}

inline flatbuffers::Offset<CreateRoomToL> CreateCreateRoomToLDirect(flatbuffers::FlatBufferBuilder &_fbb,
    int32_t Result = 0,
    const std::vector<flatbuffers::Offset<flatbuffers::String>> *Players = nullptr) {
  return CreateCreateRoomToL(_fbb, Result, Players ? _fbb.CreateVector<flatbuffers::Offset<flatbuffers::String>>(*Players) : 0);
}

}  // namespace FBS

#endif  // FLATBUFFERS_GENERATED_CREATEROOMTOL_FBS_H_
