// automatically generated by the FlatBuffers compiler, do not modify

#ifndef FLATBUFFERS_GENERATED_ENTERROOMTOC_FBS_H_
#define FLATBUFFERS_GENERATED_ENTERROOMTOC_FBS_H_

#include "flatbuffers/flatbuffers.h"

namespace FBS {

struct EnterRoomToC;

struct EnterRoomToC FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_RESULT = 4,
    VT_PLAYERINDEX = 6,
    VT_PLAYERENTITYID = 8,
    VT_PLAYERSMAPKEY = 10,
    VT_PLAYERSMAPVALUE = 12
  };
  int32_t Result() const { return GetField<int32_t>(VT_RESULT, 0); }
  int32_t PlayerIndex() const { return GetField<int32_t>(VT_PLAYERINDEX, 0); }
  int32_t PlayerEntityID() const { return GetField<int32_t>(VT_PLAYERENTITYID, 0); }
  const flatbuffers::Vector<int32_t> *PlayersMapKey() const { return GetPointer<const flatbuffers::Vector<int32_t> *>(VT_PLAYERSMAPKEY); }
  const flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>> *PlayersMapValue() const { return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>> *>(VT_PLAYERSMAPVALUE); }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_RESULT) &&
           VerifyField<int32_t>(verifier, VT_PLAYERINDEX) &&
           VerifyField<int32_t>(verifier, VT_PLAYERENTITYID) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, VT_PLAYERSMAPKEY) &&
           verifier.Verify(PlayersMapKey()) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, VT_PLAYERSMAPVALUE) &&
           verifier.Verify(PlayersMapValue()) &&
           verifier.VerifyVectorOfStrings(PlayersMapValue()) &&
           verifier.EndTable();
  }
};

struct EnterRoomToCBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_Result(int32_t Result) { fbb_.AddElement<int32_t>(EnterRoomToC::VT_RESULT, Result, 0); }
  void add_PlayerIndex(int32_t PlayerIndex) { fbb_.AddElement<int32_t>(EnterRoomToC::VT_PLAYERINDEX, PlayerIndex, 0); }
  void add_PlayerEntityID(int32_t PlayerEntityID) { fbb_.AddElement<int32_t>(EnterRoomToC::VT_PLAYERENTITYID, PlayerEntityID, 0); }
  void add_PlayersMapKey(flatbuffers::Offset<flatbuffers::Vector<int32_t>> PlayersMapKey) { fbb_.AddOffset(EnterRoomToC::VT_PLAYERSMAPKEY, PlayersMapKey); }
  void add_PlayersMapValue(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>>> PlayersMapValue) { fbb_.AddOffset(EnterRoomToC::VT_PLAYERSMAPVALUE, PlayersMapValue); }
  EnterRoomToCBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  EnterRoomToCBuilder &operator=(const EnterRoomToCBuilder &);
  flatbuffers::Offset<EnterRoomToC> Finish() {
    auto o = flatbuffers::Offset<EnterRoomToC>(fbb_.EndTable(start_, 5));
    return o;
  }
};

inline flatbuffers::Offset<EnterRoomToC> CreateEnterRoomToC(flatbuffers::FlatBufferBuilder &_fbb,
    int32_t Result = 0,
    int32_t PlayerIndex = 0,
    int32_t PlayerEntityID = 0,
    flatbuffers::Offset<flatbuffers::Vector<int32_t>> PlayersMapKey = 0,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>>> PlayersMapValue = 0) {
  EnterRoomToCBuilder builder_(_fbb);
  builder_.add_PlayersMapValue(PlayersMapValue);
  builder_.add_PlayersMapKey(PlayersMapKey);
  builder_.add_PlayerEntityID(PlayerEntityID);
  builder_.add_PlayerIndex(PlayerIndex);
  builder_.add_Result(Result);
  return builder_.Finish();
}

inline flatbuffers::Offset<EnterRoomToC> CreateEnterRoomToCDirect(flatbuffers::FlatBufferBuilder &_fbb,
    int32_t Result = 0,
    int32_t PlayerIndex = 0,
    int32_t PlayerEntityID = 0,
    const std::vector<int32_t> *PlayersMapKey = nullptr,
    const std::vector<flatbuffers::Offset<flatbuffers::String>> *PlayersMapValue = nullptr) {
  return CreateEnterRoomToC(_fbb, Result, PlayerIndex, PlayerEntityID, PlayersMapKey ? _fbb.CreateVector<int32_t>(*PlayersMapKey) : 0, PlayersMapValue ? _fbb.CreateVector<flatbuffers::Offset<flatbuffers::String>>(*PlayersMapValue) : 0);
}

}  // namespace FBS

#endif  // FLATBUFFERS_GENERATED_ENTERROOMTOC_FBS_H_
