// automatically generated by the FlatBuffers compiler, do not modify

#ifndef FLATBUFFERS_GENERATED_ENTITYCREATE_FBS_GAMEEVENT_H_
#define FLATBUFFERS_GENERATED_ENTITYCREATE_FBS_GAMEEVENT_H_

#include "flatbuffers/flatbuffers.h"

#include "FBSData_generated.h"

namespace FBS {
namespace GameEvent {

struct EntityCreate;

struct EntityCreate FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_ENTITYID = 4,
    VT_MASTERDATAID = 6,
    VT_TYPE = 8,
    VT_POS = 10,
    VT_ROT = 12
  };
  int32_t EntityID() const { return GetField<int32_t>(VT_ENTITYID, 0); }
  int32_t MasterDataID() const { return GetField<int32_t>(VT_MASTERDATAID, 0); }
  FBS::Data::EntityType Type() const { return static_cast<FBS::Data::EntityType>(GetField<int8_t>(VT_TYPE, 0)); }
  const FBS::Data::Vector3 *Pos() const { return GetStruct<const FBS::Data::Vector3 *>(VT_POS); }
  const FBS::Data::Vector3 *Rot() const { return GetStruct<const FBS::Data::Vector3 *>(VT_ROT); }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_ENTITYID) &&
           VerifyField<int32_t>(verifier, VT_MASTERDATAID) &&
           VerifyField<int8_t>(verifier, VT_TYPE) &&
           VerifyField<FBS::Data::Vector3>(verifier, VT_POS) &&
           VerifyField<FBS::Data::Vector3>(verifier, VT_ROT) &&
           verifier.EndTable();
  }
};

struct EntityCreateBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_EntityID(int32_t EntityID) { fbb_.AddElement<int32_t>(EntityCreate::VT_ENTITYID, EntityID, 0); }
  void add_MasterDataID(int32_t MasterDataID) { fbb_.AddElement<int32_t>(EntityCreate::VT_MASTERDATAID, MasterDataID, 0); }
  void add_Type(FBS::Data::EntityType Type) { fbb_.AddElement<int8_t>(EntityCreate::VT_TYPE, static_cast<int8_t>(Type), 0); }
  void add_Pos(const FBS::Data::Vector3 *Pos) { fbb_.AddStruct(EntityCreate::VT_POS, Pos); }
  void add_Rot(const FBS::Data::Vector3 *Rot) { fbb_.AddStruct(EntityCreate::VT_ROT, Rot); }
  EntityCreateBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  EntityCreateBuilder &operator=(const EntityCreateBuilder &);
  flatbuffers::Offset<EntityCreate> Finish() {
    auto o = flatbuffers::Offset<EntityCreate>(fbb_.EndTable(start_, 5));
    return o;
  }
};

inline flatbuffers::Offset<EntityCreate> CreateEntityCreate(flatbuffers::FlatBufferBuilder &_fbb,
    int32_t EntityID = 0,
    int32_t MasterDataID = 0,
    FBS::Data::EntityType Type = FBS::Data::EntityType_Character,
    const FBS::Data::Vector3 *Pos = 0,
    const FBS::Data::Vector3 *Rot = 0) {
  EntityCreateBuilder builder_(_fbb);
  builder_.add_Rot(Rot);
  builder_.add_Pos(Pos);
  builder_.add_MasterDataID(MasterDataID);
  builder_.add_EntityID(EntityID);
  builder_.add_Type(Type);
  return builder_.Finish();
}

}  // namespace GameEvent
}  // namespace FBS

#endif  // FLATBUFFERS_GENERATED_ENTITYCREATE_FBS_GAMEEVENT_H_
