// automatically generated by the FlatBuffers compiler, do not modify

#ifndef FLATBUFFERS_GENERATED_GAMEEVENTDASHTOR_FBS_H_
#define FLATBUFFERS_GENERATED_GAMEEVENTDASHTOR_FBS_H_

#include "flatbuffers/flatbuffers.h"

#include "FBSData_generated.h"

namespace FBS {

struct GameEventDashToR;

struct GameEventDashToR FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_PLAYERINDEX = 4
  };
  int32_t PlayerIndex() const { return GetField<int32_t>(VT_PLAYERINDEX, 0); }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_PLAYERINDEX) &&
           verifier.EndTable();
  }
};

struct GameEventDashToRBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_PlayerIndex(int32_t PlayerIndex) { fbb_.AddElement<int32_t>(GameEventDashToR::VT_PLAYERINDEX, PlayerIndex, 0); }
  GameEventDashToRBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  GameEventDashToRBuilder &operator=(const GameEventDashToRBuilder &);
  flatbuffers::Offset<GameEventDashToR> Finish() {
    auto o = flatbuffers::Offset<GameEventDashToR>(fbb_.EndTable(start_, 1));
    return o;
  }
};

inline flatbuffers::Offset<GameEventDashToR> CreateGameEventDashToR(flatbuffers::FlatBufferBuilder &_fbb,
    int32_t PlayerIndex = 0) {
  GameEventDashToRBuilder builder_(_fbb);
  builder_.add_PlayerIndex(PlayerIndex);
  return builder_.Finish();
}

}  // namespace FBS

#endif  // FLATBUFFERS_GENERATED_GAMEEVENTDASHTOR_FBS_H_
