// automatically generated by the FlatBuffers compiler, do not modify

#ifndef FLATBUFFERS_GENERATED_GAMEEVENTBEHAVIORSTART_H_
#define FLATBUFFERS_GENERATED_GAMEEVENTBEHAVIORSTART_H_

#include "flatbuffers/flatbuffers.h"

struct GameEvent_BehaviorStart;

struct GameEvent_BehaviorStart FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_ENTITYID = 4,
    VT_STARTTIME = 6,
    VT_BEHAVIORID = 8
  };
  int32_t EntityID() const { return GetField<int32_t>(VT_ENTITYID, 0); }
  float StartTime() const { return GetField<float>(VT_STARTTIME, 0.0f); }
  int32_t BehaviorID() const { return GetField<int32_t>(VT_BEHAVIORID, 0); }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_ENTITYID) &&
           VerifyField<float>(verifier, VT_STARTTIME) &&
           VerifyField<int32_t>(verifier, VT_BEHAVIORID) &&
           verifier.EndTable();
  }
};

struct GameEvent_BehaviorStartBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_EntityID(int32_t EntityID) { fbb_.AddElement<int32_t>(GameEvent_BehaviorStart::VT_ENTITYID, EntityID, 0); }
  void add_StartTime(float StartTime) { fbb_.AddElement<float>(GameEvent_BehaviorStart::VT_STARTTIME, StartTime, 0.0f); }
  void add_BehaviorID(int32_t BehaviorID) { fbb_.AddElement<int32_t>(GameEvent_BehaviorStart::VT_BEHAVIORID, BehaviorID, 0); }
  GameEvent_BehaviorStartBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  GameEvent_BehaviorStartBuilder &operator=(const GameEvent_BehaviorStartBuilder &);
  flatbuffers::Offset<GameEvent_BehaviorStart> Finish() {
    auto o = flatbuffers::Offset<GameEvent_BehaviorStart>(fbb_.EndTable(start_, 3));
    return o;
  }
};

inline flatbuffers::Offset<GameEvent_BehaviorStart> CreateGameEvent_BehaviorStart(flatbuffers::FlatBufferBuilder &_fbb,
    int32_t EntityID = 0,
    float StartTime = 0.0f,
    int32_t BehaviorID = 0) {
  GameEvent_BehaviorStartBuilder builder_(_fbb);
  builder_.add_BehaviorID(BehaviorID);
  builder_.add_StartTime(StartTime);
  builder_.add_EntityID(EntityID);
  return builder_.Finish();
}

#endif  // FLATBUFFERS_GENERATED_GAMEEVENTBEHAVIORSTART_H_
