// automatically generated by the FlatBuffers compiler, do not modify

#ifndef FLATBUFFERS_GENERATED_GAMEEVENTSTOPTOR_FBS_H_
#define FLATBUFFERS_GENERATED_GAMEEVENTSTOPTOR_FBS_H_

#include "flatbuffers/flatbuffers.h"

#include "FBSData_generated.h"

namespace FBS {

struct GameEventStopToR;

struct GameEventStopToR FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_PLAYERINDEX = 4,
    VT_POS = 6
  };
  int32_t PlayerIndex() const { return GetField<int32_t>(VT_PLAYERINDEX, 0); }
  const FBS::Data::Vector3 *Pos() const { return GetStruct<const FBS::Data::Vector3 *>(VT_POS); }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_PLAYERINDEX) &&
           VerifyField<FBS::Data::Vector3>(verifier, VT_POS) &&
           verifier.EndTable();
  }
};

struct GameEventStopToRBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_PlayerIndex(int32_t PlayerIndex) { fbb_.AddElement<int32_t>(GameEventStopToR::VT_PLAYERINDEX, PlayerIndex, 0); }
  void add_Pos(const FBS::Data::Vector3 *Pos) { fbb_.AddStruct(GameEventStopToR::VT_POS, Pos); }
  GameEventStopToRBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  GameEventStopToRBuilder &operator=(const GameEventStopToRBuilder &);
  flatbuffers::Offset<GameEventStopToR> Finish() {
    auto o = flatbuffers::Offset<GameEventStopToR>(fbb_.EndTable(start_, 2));
    return o;
  }
};

inline flatbuffers::Offset<GameEventStopToR> CreateGameEventStopToR(flatbuffers::FlatBufferBuilder &_fbb,
    int32_t PlayerIndex = 0,
    const FBS::Data::Vector3 *Pos = 0) {
  GameEventStopToRBuilder builder_(_fbb);
  builder_.add_Pos(Pos);
  builder_.add_PlayerIndex(PlayerIndex);
  return builder_.Finish();
}

}  // namespace FBS

#endif  // FLATBUFFERS_GENERATED_GAMEEVENTSTOPTOR_FBS_H_
