// automatically generated by the FlatBuffers compiler, do not modify

#ifndef FLATBUFFERS_GENERATED_GAMEEVENTMOVETOR_FBS_H_
#define FLATBUFFERS_GENERATED_GAMEEVENTMOVETOR_FBS_H_

#include "flatbuffers/flatbuffers.h"

#include "FBSData_generated.h"

namespace FBS {

struct GameEventMoveToR;

struct GameEventMoveToR FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_PLAYERINDEX = 4,
    VT_DEST = 6
  };
  int32_t PlayerIndex() const { return GetField<int32_t>(VT_PLAYERINDEX, 0); }
  const FBS::Data::Vector3 *Dest() const { return GetStruct<const FBS::Data::Vector3 *>(VT_DEST); }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_PLAYERINDEX) &&
           VerifyField<FBS::Data::Vector3>(verifier, VT_DEST) &&
           verifier.EndTable();
  }
};

struct GameEventMoveToRBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_PlayerIndex(int32_t PlayerIndex) { fbb_.AddElement<int32_t>(GameEventMoveToR::VT_PLAYERINDEX, PlayerIndex, 0); }
  void add_Dest(const FBS::Data::Vector3 *Dest) { fbb_.AddStruct(GameEventMoveToR::VT_DEST, Dest); }
  GameEventMoveToRBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  GameEventMoveToRBuilder &operator=(const GameEventMoveToRBuilder &);
  flatbuffers::Offset<GameEventMoveToR> Finish() {
    auto o = flatbuffers::Offset<GameEventMoveToR>(fbb_.EndTable(start_, 2));
    return o;
  }
};

inline flatbuffers::Offset<GameEventMoveToR> CreateGameEventMoveToR(flatbuffers::FlatBufferBuilder &_fbb,
    int32_t PlayerIndex = 0,
    const FBS::Data::Vector3 *Dest = 0) {
  GameEventMoveToRBuilder builder_(_fbb);
  builder_.add_Dest(Dest);
  builder_.add_PlayerIndex(PlayerIndex);
  return builder_.Finish();
}

}  // namespace FBS

#endif  // FLATBUFFERS_GENERATED_GAMEEVENTMOVETOR_FBS_H_
