// automatically generated by the FlatBuffers compiler, do not modify

#ifndef FLATBUFFERS_GENERATED_JOINLOBBYTOLDATA_H_
#define FLATBUFFERS_GENERATED_JOINLOBBYTOLDATA_H_

#include "flatbuffers/flatbuffers.h"

struct JoinLobbyToL_Data;

struct JoinLobbyToL_Data FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_PLAYERKEY = 4,
    VT_AUTHKEY = 6
  };
  const flatbuffers::String *PlayerKey() const { return GetPointer<const flatbuffers::String *>(VT_PLAYERKEY); }
  int32_t AuthKey() const { return GetField<int32_t>(VT_AUTHKEY, 0); }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, VT_PLAYERKEY) &&
           verifier.Verify(PlayerKey()) &&
           VerifyField<int32_t>(verifier, VT_AUTHKEY) &&
           verifier.EndTable();
  }
};

struct JoinLobbyToL_DataBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_PlayerKey(flatbuffers::Offset<flatbuffers::String> PlayerKey) { fbb_.AddOffset(JoinLobbyToL_Data::VT_PLAYERKEY, PlayerKey); }
  void add_AuthKey(int32_t AuthKey) { fbb_.AddElement<int32_t>(JoinLobbyToL_Data::VT_AUTHKEY, AuthKey, 0); }
  JoinLobbyToL_DataBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  JoinLobbyToL_DataBuilder &operator=(const JoinLobbyToL_DataBuilder &);
  flatbuffers::Offset<JoinLobbyToL_Data> Finish() {
    auto o = flatbuffers::Offset<JoinLobbyToL_Data>(fbb_.EndTable(start_, 2));
    return o;
  }
};

inline flatbuffers::Offset<JoinLobbyToL_Data> CreateJoinLobbyToL_Data(flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::String> PlayerKey = 0,
    int32_t AuthKey = 0) {
  JoinLobbyToL_DataBuilder builder_(_fbb);
  builder_.add_AuthKey(AuthKey);
  builder_.add_PlayerKey(PlayerKey);
  return builder_.Finish();
}

inline flatbuffers::Offset<JoinLobbyToL_Data> CreateJoinLobbyToL_DataDirect(flatbuffers::FlatBufferBuilder &_fbb,
    const char *PlayerKey = nullptr,
    int32_t AuthKey = 0) {
  return CreateJoinLobbyToL_Data(_fbb, PlayerKey ? _fbb.CreateString(PlayerKey) : 0, AuthKey);
}

#endif  // FLATBUFFERS_GENERATED_JOINLOBBYTOLDATA_H_
