// automatically generated by the FlatBuffers compiler, do not modify

#ifndef FLATBUFFERS_GENERATED_PLAYERINPUTDATA_FBS_H_
#define FLATBUFFERS_GENERATED_PLAYERINPUTDATA_FBS_H_

#include "flatbuffers/flatbuffers.h"

namespace FBS {

struct PlayerInputData;

enum PlayerInputType {
  PlayerInputType_Position = 0,
  PlayerInputType_Rotation = 1,
  PlayerInputType_MIN = PlayerInputType_Position,
  PlayerInputType_MAX = PlayerInputType_Rotation
};

inline const char **EnumNamesPlayerInputType() {
  static const char *names[] = { "Position", "Rotation", nullptr };
  return names;
}

inline const char *EnumNamePlayerInputType(PlayerInputType e) { return EnumNamesPlayerInputType()[static_cast<int>(e)]; }

struct PlayerInputData FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_TYPE = 4,
    VT_DATA = 6
  };
  PlayerInputType Type() const { return static_cast<PlayerInputType>(GetField<int8_t>(VT_TYPE, 0)); }
  const flatbuffers::Vector<int8_t> *Data() const { return GetPointer<const flatbuffers::Vector<int8_t> *>(VT_DATA); }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int8_t>(verifier, VT_TYPE) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, VT_DATA) &&
           verifier.Verify(Data()) &&
           verifier.EndTable();
  }
};

struct PlayerInputDataBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_Type(PlayerInputType Type) { fbb_.AddElement<int8_t>(PlayerInputData::VT_TYPE, static_cast<int8_t>(Type), 0); }
  void add_Data(flatbuffers::Offset<flatbuffers::Vector<int8_t>> Data) { fbb_.AddOffset(PlayerInputData::VT_DATA, Data); }
  PlayerInputDataBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  PlayerInputDataBuilder &operator=(const PlayerInputDataBuilder &);
  flatbuffers::Offset<PlayerInputData> Finish() {
    auto o = flatbuffers::Offset<PlayerInputData>(fbb_.EndTable(start_, 2));
    return o;
  }
};

inline flatbuffers::Offset<PlayerInputData> CreatePlayerInputData(flatbuffers::FlatBufferBuilder &_fbb,
    PlayerInputType Type = PlayerInputType_Position,
    flatbuffers::Offset<flatbuffers::Vector<int8_t>> Data = 0) {
  PlayerInputDataBuilder builder_(_fbb);
  builder_.add_Data(Data);
  builder_.add_Type(Type);
  return builder_.Finish();
}

inline flatbuffers::Offset<PlayerInputData> CreatePlayerInputDataDirect(flatbuffers::FlatBufferBuilder &_fbb,
    PlayerInputType Type = PlayerInputType_Position,
    const std::vector<int8_t> *Data = nullptr) {
  return CreatePlayerInputData(_fbb, Type, Data ? _fbb.CreateVector<int8_t>(*Data) : 0);
}

}  // namespace FBS

#endif  // FLATBUFFERS_GENERATED_PLAYERINPUTDATA_FBS_H_
