// automatically generated by the FlatBuffers compiler, do not modify

#ifndef FLATBUFFERS_GENERATED_READYFORSTARTTORDATA_H_
#define FLATBUFFERS_GENERATED_READYFORSTARTTORDATA_H_

#include "flatbuffers/flatbuffers.h"

struct ReadyForStartToR_Data;

struct ReadyForStartToR_Data FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_PLAYERINDEX = 4
  };
  int32_t PlayerIndex() const { return GetField<int32_t>(VT_PLAYERINDEX, 0); }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_PLAYERINDEX) &&
           verifier.EndTable();
  }
};

struct ReadyForStartToR_DataBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_PlayerIndex(int32_t PlayerIndex) { fbb_.AddElement<int32_t>(ReadyForStartToR_Data::VT_PLAYERINDEX, PlayerIndex, 0); }
  ReadyForStartToR_DataBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  ReadyForStartToR_DataBuilder &operator=(const ReadyForStartToR_DataBuilder &);
  flatbuffers::Offset<ReadyForStartToR_Data> Finish() {
    auto o = flatbuffers::Offset<ReadyForStartToR_Data>(fbb_.EndTable(start_, 1));
    return o;
  }
};

inline flatbuffers::Offset<ReadyForStartToR_Data> CreateReadyForStartToR_Data(flatbuffers::FlatBufferBuilder &_fbb,
    int32_t PlayerIndex = 0) {
  ReadyForStartToR_DataBuilder builder_(_fbb);
  builder_.add_PlayerIndex(PlayerIndex);
  return builder_.Finish();
}

#endif  // FLATBUFFERS_GENERATED_READYFORSTARTTORDATA_H_
