// automatically generated by the FlatBuffers compiler, do not modify

#ifndef FLATBUFFERS_GENERATED_SELECTNORMALGAMETOL_FBS_H_
#define FLATBUFFERS_GENERATED_SELECTNORMALGAMETOL_FBS_H_

#include "flatbuffers/flatbuffers.h"

namespace FBS {

struct SelectNormalGameToL;

struct SelectNormalGameToL FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           verifier.EndTable();
  }
};

struct SelectNormalGameToLBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  SelectNormalGameToLBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  SelectNormalGameToLBuilder &operator=(const SelectNormalGameToLBuilder &);
  flatbuffers::Offset<SelectNormalGameToL> Finish() {
    auto o = flatbuffers::Offset<SelectNormalGameToL>(fbb_.EndTable(start_, 0));
    return o;
  }
};

inline flatbuffers::Offset<SelectNormalGameToL> CreateSelectNormalGameToL(flatbuffers::FlatBufferBuilder &_fbb) {
  SelectNormalGameToLBuilder builder_(_fbb);
  return builder_.Finish();
}

}  // namespace FBS

#endif  // FLATBUFFERS_GENERATED_SELECTNORMALGAMETOL_FBS_H_
