// automatically generated by the FlatBuffers compiler, do not modify

#ifndef FLATBUFFERS_GENERATED_SELECTNORMALGAMETOCDATA_H_
#define FLATBUFFERS_GENERATED_SELECTNORMALGAMETOCDATA_H_

#include "flatbuffers/flatbuffers.h"

struct SelectNormalGameToC_Data;

struct SelectNormalGameToC_Data FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_RESULT = 4,
    VT_EXPECTEDTIME = 6
  };
  int32_t Result() const { return GetField<int32_t>(VT_RESULT, 0); }
  int32_t ExpectedTime() const { return GetField<int32_t>(VT_EXPECTEDTIME, 0); }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_RESULT) &&
           VerifyField<int32_t>(verifier, VT_EXPECTEDTIME) &&
           verifier.EndTable();
  }
};

struct SelectNormalGameToC_DataBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_Result(int32_t Result) { fbb_.AddElement<int32_t>(SelectNormalGameToC_Data::VT_RESULT, Result, 0); }
  void add_ExpectedTime(int32_t ExpectedTime) { fbb_.AddElement<int32_t>(SelectNormalGameToC_Data::VT_EXPECTEDTIME, ExpectedTime, 0); }
  SelectNormalGameToC_DataBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  SelectNormalGameToC_DataBuilder &operator=(const SelectNormalGameToC_DataBuilder &);
  flatbuffers::Offset<SelectNormalGameToC_Data> Finish() {
    auto o = flatbuffers::Offset<SelectNormalGameToC_Data>(fbb_.EndTable(start_, 2));
    return o;
  }
};

inline flatbuffers::Offset<SelectNormalGameToC_Data> CreateSelectNormalGameToC_Data(flatbuffers::FlatBufferBuilder &_fbb,
    int32_t Result = 0,
    int32_t ExpectedTime = 0) {
  SelectNormalGameToC_DataBuilder builder_(_fbb);
  builder_.add_ExpectedTime(ExpectedTime);
  builder_.add_Result(Result);
  return builder_.Finish();
}

#endif  // FLATBUFFERS_GENERATED_SELECTNORMALGAMETOCDATA_H_
