// automatically generated by the FlatBuffers compiler, do not modify

namespace FBS
{

using System;
using FlatBuffers;

public sealed class EnterRoomToR : Table {
  public static EnterRoomToR GetRootAsEnterRoomToR(ByteBuffer _bb) { return GetRootAsEnterRoomToR(_bb, new EnterRoomToR()); }
  public static EnterRoomToR GetRootAsEnterRoomToR(ByteBuffer _bb, EnterRoomToR obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public EnterRoomToR __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public string PlayerKey { get { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; } }
  public ArraySegment<byte>? GetPlayerKeyBytes() { return __vector_as_arraysegment(4); }
  public int AuthKey { get { int o = __offset(6); return o != 0 ? bb.GetInt(o + bb_pos) : (int)0; } }
  public int MatchID { get { int o = __offset(8); return o != 0 ? bb.GetInt(o + bb_pos) : (int)0; } }

  public static Offset<EnterRoomToR> CreateEnterRoomToR(FlatBufferBuilder builder,
      StringOffset PlayerKeyOffset = default(StringOffset),
      int AuthKey = 0,
      int MatchID = 0) {
    builder.StartObject(3);
    EnterRoomToR.AddMatchID(builder, MatchID);
    EnterRoomToR.AddAuthKey(builder, AuthKey);
    EnterRoomToR.AddPlayerKey(builder, PlayerKeyOffset);
    return EnterRoomToR.EndEnterRoomToR(builder);
  }

  public static void StartEnterRoomToR(FlatBufferBuilder builder) { builder.StartObject(3); }
  public static void AddPlayerKey(FlatBufferBuilder builder, StringOffset PlayerKeyOffset) { builder.AddOffset(0, PlayerKeyOffset.Value, 0); }
  public static void AddAuthKey(FlatBufferBuilder builder, int AuthKey) { builder.AddInt(1, AuthKey, 0); }
  public static void AddMatchID(FlatBufferBuilder builder, int MatchID) { builder.AddInt(2, MatchID, 0); }
  public static Offset<EnterRoomToR> EndEnterRoomToR(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<EnterRoomToR>(o);
  }
};


}
