// automatically generated by the FlatBuffers compiler, do not modify

namespace FBS
{

using System;
using FlatBuffers;

public sealed class GameStartToC : Table {
  public static GameStartToC GetRootAsGameStartToC(ByteBuffer _bb) { return GetRootAsGameStartToC(_bb, new GameStartToC()); }
  public static GameStartToC GetRootAsGameStartToC(ByteBuffer _bb, GameStartToC obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public GameStartToC __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }


  public static void StartGameStartToC(FlatBufferBuilder builder) { builder.StartObject(0); }
  public static Offset<GameStartToC> EndGameStartToC(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<GameStartToC>(o);
  }
};


}
