// automatically generated by the FlatBuffers compiler, do not modify

namespace FBS
{

public enum GameEventType : sbyte
{
 BehaviorStart = 0,
 BehaviorEnd = 1,
 StateStart = 2,
 StateEnd = 3,
 Position = 4,
 Rotation = 5,
 CharacterAttack = 6,
 CharacterRespawn = 7,
 CharacterStatusChange = 8,
 EntityCreate = 9,
 EntityDestroy = 10,
};


}
