// automatically generated by the FlatBuffers compiler, do not modify

namespace FBS
{

using System;
using FlatBuffers;

public sealed class GameResultToR : Table {
  public static GameResultToR GetRootAsGameResultToR(ByteBuffer _bb) { return GetRootAsGameResultToR(_bb, new GameResultToR()); }
  public static GameResultToR GetRootAsGameResultToR(ByteBuffer _bb, GameResultToR obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public GameResultToR __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public FBS.Data.PlayerRankInfo GetPlayerRanks(int j) { return GetPlayerRanks(new FBS.Data.PlayerRankInfo(), j); }
  public FBS.Data.PlayerRankInfo GetPlayerRanks(FBS.Data.PlayerRankInfo obj, int j) { int o = __offset(4); return o != 0 ? obj.__init(__vector(o) + j * 12, bb) : null; }
  public int PlayerRanksLength { get { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; } }

  public static Offset<GameResultToR> CreateGameResultToR(FlatBufferBuilder builder,
      VectorOffset PlayerRanksOffset = default(VectorOffset)) {
    builder.StartObject(1);
    GameResultToR.AddPlayerRanks(builder, PlayerRanksOffset);
    return GameResultToR.EndGameResultToR(builder);
  }

  public static void StartGameResultToR(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddPlayerRanks(FlatBufferBuilder builder, VectorOffset PlayerRanksOffset) { builder.AddOffset(0, PlayerRanksOffset.Value, 0); }
  public static void StartPlayerRanksVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(12, numElems, 4); }
  public static Offset<GameResultToR> EndGameResultToR(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<GameResultToR>(o);
  }
};


}
