// automatically generated by the FlatBuffers compiler, do not modify

namespace FBS
{

using System;
using FlatBuffers;

public sealed class GameEndToC : Table {
  public static GameEndToC GetRootAsGameEndToC(ByteBuffer _bb) { return GetRootAsGameEndToC(_bb, new GameEndToC()); }
  public static GameEndToC GetRootAsGameEndToC(ByteBuffer _bb, GameEndToC obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public GameEndToC __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public FBS.Data.PlayerRankInfo GetPlayerRanks(int j) { return GetPlayerRanks(new FBS.Data.PlayerRankInfo(), j); }
  public FBS.Data.PlayerRankInfo GetPlayerRanks(FBS.Data.PlayerRankInfo obj, int j) { int o = __offset(4); return o != 0 ? obj.__init(__vector(o) + j * 12, bb) : null; }
  public int PlayerRanksLength { get { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; } }

  public static Offset<GameEndToC> CreateGameEndToC(FlatBufferBuilder builder,
      VectorOffset PlayerRanksOffset = default(VectorOffset)) {
    builder.StartObject(1);
    GameEndToC.AddPlayerRanks(builder, PlayerRanksOffset);
    return GameEndToC.EndGameEndToC(builder);
  }

  public static void StartGameEndToC(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddPlayerRanks(FlatBufferBuilder builder, VectorOffset PlayerRanksOffset) { builder.AddOffset(0, PlayerRanksOffset.Value, 0); }
  public static void StartPlayerRanksVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(12, numElems, 4); }
  public static Offset<GameEndToC> EndGameEndToC(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<GameEndToC>(o);
  }
};


}
