// automatically generated by the FlatBuffers compiler, do not modify

namespace FBS
{

public enum GameEventType : sbyte
{
 BehaviorStart = 0,
 BehaviorEnd = 1,
 StateStart = 2,
 StateEnd = 3,
 Position = 4,
 Rotation = 5,
 Collision = 6,
 EntityCreate = 7,
 EntityDestroy = 8,
};


}
