// automatically generated by the FlatBuffers compiler, do not modify

namespace FBS
{

using System;
using FlatBuffers;

public sealed class GameEventStopToR : Table {
  public static GameEventStopToR GetRootAsGameEventStopToR(ByteBuffer _bb) { return GetRootAsGameEventStopToR(_bb, new GameEventStopToR()); }
  public static GameEventStopToR GetRootAsGameEventStopToR(ByteBuffer _bb, GameEventStopToR obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public GameEventStopToR __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public int PlayerIndex { get { int o = __offset(4); return o != 0 ? bb.GetInt(o + bb_pos) : (int)0; } }
  public FBS.Data.Vector3 Pos { get { return GetPos(new FBS.Data.Vector3()); } }
  public FBS.Data.Vector3 GetPos(FBS.Data.Vector3 obj) { int o = __offset(6); return o != 0 ? obj.__init(o + bb_pos, bb) : null; }

  public static void StartGameEventStopToR(FlatBufferBuilder builder) { builder.StartObject(2); }
  public static void AddPlayerIndex(FlatBufferBuilder builder, int PlayerIndex) { builder.AddInt(0, PlayerIndex, 0); }
  public static void AddPos(FlatBufferBuilder builder, Offset<FBS.Data.Vector3> PosOffset) { builder.AddStruct(1, PosOffset.Value, 0); }
  public static Offset<GameEventStopToR> EndGameEventStopToR(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<GameEventStopToR>(o);
  }
};


}
