// automatically generated by the FlatBuffers compiler, do not modify

namespace FBS
{

using System;
using FlatBuffers;

public sealed class JoinLobbyToC : Table {
  public static JoinLobbyToC GetRootAsJoinLobbyToC(ByteBuffer _bb) { return GetRootAsJoinLobbyToC(_bb, new JoinLobbyToC()); }
  public static JoinLobbyToC GetRootAsJoinLobbyToC(ByteBuffer _bb, JoinLobbyToC obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public JoinLobbyToC __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public int Result { get { int o = __offset(4); return o != 0 ? bb.GetInt(o + bb_pos) : (int)0; } }

  public static Offset<JoinLobbyToC> CreateJoinLobbyToC(FlatBufferBuilder builder,
      int Result = 0) {
    builder.StartObject(1);
    JoinLobbyToC.AddResult(builder, Result);
    return JoinLobbyToC.EndJoinLobbyToC(builder);
  }

  public static void StartJoinLobbyToC(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddResult(FlatBufferBuilder builder, int Result) { builder.AddInt(0, Result, 0); }
  public static Offset<JoinLobbyToC> EndJoinLobbyToC(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<JoinLobbyToC>(o);
  }
};


}
