// automatically generated by the FlatBuffers compiler, do not modify

namespace FBS
{

using System;
using FlatBuffers;

public sealed class SelectNormalGameToL : Table {
  public static SelectNormalGameToL GetRootAsSelectNormalGameToL(ByteBuffer _bb) { return GetRootAsSelectNormalGameToL(_bb, new SelectNormalGameToL()); }
  public static SelectNormalGameToL GetRootAsSelectNormalGameToL(ByteBuffer _bb, SelectNormalGameToL obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public SelectNormalGameToL __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }


  public static void StartSelectNormalGameToL(FlatBufferBuilder builder) { builder.StartObject(0); }
  public static Offset<SelectNormalGameToL> EndSelectNormalGameToL(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<SelectNormalGameToL>(o);
  }
};


}
