// automatically generated by the FlatBuffers compiler, do not modify

#ifndef FLATBUFFERS_GENERATED_BEHAVIOREND_FBS_GAMEEVENT_H_
#define FLATBUFFERS_GENERATED_BEHAVIOREND_FBS_GAMEEVENT_H_

#include "flatbuffers/flatbuffers.h"

namespace FBS {
namespace GameEvent {

struct BehaviorEnd;

struct BehaviorEnd FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_ENTITYID = 4,
    VT_ENDTIME = 6,
    VT_BEHAVIORID = 8
  };
  int32_t EntityID() const { return GetField<int32_t>(VT_ENTITYID, 0); }
  float EndTime() const { return GetField<float>(VT_ENDTIME, 0.0f); }
  int32_t BehaviorID() const { return GetField<int32_t>(VT_BEHAVIORID, 0); }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_ENTITYID) &&
           VerifyField<float>(verifier, VT_ENDTIME) &&
           VerifyField<int32_t>(verifier, VT_BEHAVIORID) &&
           verifier.EndTable();
  }
};

struct BehaviorEndBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_EntityID(int32_t EntityID) { fbb_.AddElement<int32_t>(BehaviorEnd::VT_ENTITYID, EntityID, 0); }
  void add_EndTime(float EndTime) { fbb_.AddElement<float>(BehaviorEnd::VT_ENDTIME, EndTime, 0.0f); }
  void add_BehaviorID(int32_t BehaviorID) { fbb_.AddElement<int32_t>(BehaviorEnd::VT_BEHAVIORID, BehaviorID, 0); }
  BehaviorEndBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  BehaviorEndBuilder &operator=(const BehaviorEndBuilder &);
  flatbuffers::Offset<BehaviorEnd> Finish() {
    auto o = flatbuffers::Offset<BehaviorEnd>(fbb_.EndTable(start_, 3));
    return o;
  }
};

inline flatbuffers::Offset<BehaviorEnd> CreateBehaviorEnd(flatbuffers::FlatBufferBuilder &_fbb,
    int32_t EntityID = 0,
    float EndTime = 0.0f,
    int32_t BehaviorID = 0) {
  BehaviorEndBuilder builder_(_fbb);
  builder_.add_BehaviorID(BehaviorID);
  builder_.add_EndTime(EndTime);
  builder_.add_EntityID(EntityID);
  return builder_.Finish();
}

}  // namespace GameEvent
}  // namespace FBS

#endif  // FLATBUFFERS_GENERATED_BEHAVIOREND_FBS_GAMEEVENT_H_
