// automatically generated by the FlatBuffers compiler, do not modify

#ifndef FLATBUFFERS_GENERATED_ENTITYDESTROY_FBS_GAMEEVENT_H_
#define FLATBUFFERS_GENERATED_ENTITYDESTROY_FBS_GAMEEVENT_H_

#include "flatbuffers/flatbuffers.h"

namespace FBS {
namespace GameEvent {

struct EntityDestroy;

struct EntityDestroy FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_ENTITYID = 4
  };
  int32_t EntityID() const { return GetField<int32_t>(VT_ENTITYID, 0); }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_ENTITYID) &&
           verifier.EndTable();
  }
};

struct EntityDestroyBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_EntityID(int32_t EntityID) { fbb_.AddElement<int32_t>(EntityDestroy::VT_ENTITYID, EntityID, 0); }
  EntityDestroyBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  EntityDestroyBuilder &operator=(const EntityDestroyBuilder &);
  flatbuffers::Offset<EntityDestroy> Finish() {
    auto o = flatbuffers::Offset<EntityDestroy>(fbb_.EndTable(start_, 1));
    return o;
  }
};

inline flatbuffers::Offset<EntityDestroy> CreateEntityDestroy(flatbuffers::FlatBufferBuilder &_fbb,
    int32_t EntityID = 0) {
  EntityDestroyBuilder builder_(_fbb);
  builder_.add_EntityID(EntityID);
  return builder_.Finish();
}

}  // namespace GameEvent
}  // namespace FBS

#endif  // FLATBUFFERS_GENERATED_ENTITYDESTROY_FBS_GAMEEVENT_H_
