// automatically generated by the FlatBuffers compiler, do not modify

#ifndef FLATBUFFERS_GENERATED_GAMESTARTTOC_FBS_H_
#define FLATBUFFERS_GENERATED_GAMESTARTTOC_FBS_H_

#include "flatbuffers/flatbuffers.h"

namespace FBS {

struct GameStartToC;

struct GameStartToC FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           verifier.EndTable();
  }
};

struct GameStartToCBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  GameStartToCBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  GameStartToCBuilder &operator=(const GameStartToCBuilder &);
  flatbuffers::Offset<GameStartToC> Finish() {
    auto o = flatbuffers::Offset<GameStartToC>(fbb_.EndTable(start_, 0));
    return o;
  }
};

inline flatbuffers::Offset<GameStartToC> CreateGameStartToC(flatbuffers::FlatBufferBuilder &_fbb) {
  GameStartToCBuilder builder_(_fbb);
  return builder_.Finish();
}

}  // namespace FBS

#endif  // FLATBUFFERS_GENERATED_GAMESTARTTOC_FBS_H_
