// automatically generated by the FlatBuffers compiler, do not modify

#ifndef FLATBUFFERS_GENERATED_GAMEENDTOC_FBS_H_
#define FLATBUFFERS_GENERATED_GAMEENDTOC_FBS_H_

#include "flatbuffers/flatbuffers.h"

#include "FBSData_generated.h"

namespace FBS {

struct GameEndToC;

struct GameEndToC FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_PLAYERRANKS = 4
  };
  const flatbuffers::Vector<const FBS::Data::PlayerRankInfo *> *PlayerRanks() const { return GetPointer<const flatbuffers::Vector<const FBS::Data::PlayerRankInfo *> *>(VT_PLAYERRANKS); }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, VT_PLAYERRANKS) &&
           verifier.Verify(PlayerRanks()) &&
           verifier.EndTable();
  }
};

struct GameEndToCBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_PlayerRanks(flatbuffers::Offset<flatbuffers::Vector<const FBS::Data::PlayerRankInfo *>> PlayerRanks) { fbb_.AddOffset(GameEndToC::VT_PLAYERRANKS, PlayerRanks); }
  GameEndToCBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  GameEndToCBuilder &operator=(const GameEndToCBuilder &);
  flatbuffers::Offset<GameEndToC> Finish() {
    auto o = flatbuffers::Offset<GameEndToC>(fbb_.EndTable(start_, 1));
    return o;
  }
};

inline flatbuffers::Offset<GameEndToC> CreateGameEndToC(flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::Vector<const FBS::Data::PlayerRankInfo *>> PlayerRanks = 0) {
  GameEndToCBuilder builder_(_fbb);
  builder_.add_PlayerRanks(PlayerRanks);
  return builder_.Finish();
}

inline flatbuffers::Offset<GameEndToC> CreateGameEndToCDirect(flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<const FBS::Data::PlayerRankInfo *> *PlayerRanks = nullptr) {
  return CreateGameEndToC(_fbb, PlayerRanks ? _fbb.CreateVector<const FBS::Data::PlayerRankInfo *>(*PlayerRanks) : 0);
}

}  // namespace FBS

#endif  // FLATBUFFERS_GENERATED_GAMEENDTOC_FBS_H_
