// automatically generated by the FlatBuffers compiler, do not modify

#ifndef FLATBUFFERS_GENERATED_GAMERESULTTOR_FBS_H_
#define FLATBUFFERS_GENERATED_GAMERESULTTOR_FBS_H_

#include "flatbuffers/flatbuffers.h"

#include "FBSData_generated.h"

namespace FBS {

struct GameResultToR;

struct GameResultToR FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_PLAYERRANKS = 4
  };
  const flatbuffers::Vector<const FBS::Data::PlayerRankInfo *> *PlayerRanks() const { return GetPointer<const flatbuffers::Vector<const FBS::Data::PlayerRankInfo *> *>(VT_PLAYERRANKS); }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, VT_PLAYERRANKS) &&
           verifier.Verify(PlayerRanks()) &&
           verifier.EndTable();
  }
};

struct GameResultToRBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_PlayerRanks(flatbuffers::Offset<flatbuffers::Vector<const FBS::Data::PlayerRankInfo *>> PlayerRanks) { fbb_.AddOffset(GameResultToR::VT_PLAYERRANKS, PlayerRanks); }
  GameResultToRBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  GameResultToRBuilder &operator=(const GameResultToRBuilder &);
  flatbuffers::Offset<GameResultToR> Finish() {
    auto o = flatbuffers::Offset<GameResultToR>(fbb_.EndTable(start_, 1));
    return o;
  }
};

inline flatbuffers::Offset<GameResultToR> CreateGameResultToR(flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::Vector<const FBS::Data::PlayerRankInfo *>> PlayerRanks = 0) {
  GameResultToRBuilder builder_(_fbb);
  builder_.add_PlayerRanks(PlayerRanks);
  return builder_.Finish();
}

inline flatbuffers::Offset<GameResultToR> CreateGameResultToRDirect(flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<const FBS::Data::PlayerRankInfo *> *PlayerRanks = nullptr) {
  return CreateGameResultToR(_fbb, PlayerRanks ? _fbb.CreateVector<const FBS::Data::PlayerRankInfo *>(*PlayerRanks) : 0);
}

}  // namespace FBS

#endif  // FLATBUFFERS_GENERATED_GAMERESULTTOR_FBS_H_
