// automatically generated by the FlatBuffers compiler, do not modify

#ifndef FLATBUFFERS_GENERATED_POSITION_FBS_GAMEEVENT_H_
#define FLATBUFFERS_GENERATED_POSITION_FBS_GAMEEVENT_H_

#include "flatbuffers/flatbuffers.h"

#include "FBSData_generated.h"

namespace FBS {
namespace GameEvent {

struct Position;

struct Position FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_ENTITYID = 4,
    VT_STARTTIME = 6,
    VT_ENDTIME = 8,
    VT_STARTPOS = 10,
    VT_ENDPOS = 12
  };
  int32_t EntityID() const { return GetField<int32_t>(VT_ENTITYID, 0); }
  float StartTime() const { return GetField<float>(VT_STARTTIME, 0.0f); }
  float EndTime() const { return GetField<float>(VT_ENDTIME, 0.0f); }
  const FBS::Data::Vector3 *StartPos() const { return GetStruct<const FBS::Data::Vector3 *>(VT_STARTPOS); }
  const FBS::Data::Vector3 *EndPos() const { return GetStruct<const FBS::Data::Vector3 *>(VT_ENDPOS); }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_ENTITYID) &&
           VerifyField<float>(verifier, VT_STARTTIME) &&
           VerifyField<float>(verifier, VT_ENDTIME) &&
           VerifyField<FBS::Data::Vector3>(verifier, VT_STARTPOS) &&
           VerifyField<FBS::Data::Vector3>(verifier, VT_ENDPOS) &&
           verifier.EndTable();
  }
};

struct PositionBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_EntityID(int32_t EntityID) { fbb_.AddElement<int32_t>(Position::VT_ENTITYID, EntityID, 0); }
  void add_StartTime(float StartTime) { fbb_.AddElement<float>(Position::VT_STARTTIME, StartTime, 0.0f); }
  void add_EndTime(float EndTime) { fbb_.AddElement<float>(Position::VT_ENDTIME, EndTime, 0.0f); }
  void add_StartPos(const FBS::Data::Vector3 *StartPos) { fbb_.AddStruct(Position::VT_STARTPOS, StartPos); }
  void add_EndPos(const FBS::Data::Vector3 *EndPos) { fbb_.AddStruct(Position::VT_ENDPOS, EndPos); }
  PositionBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  PositionBuilder &operator=(const PositionBuilder &);
  flatbuffers::Offset<Position> Finish() {
    auto o = flatbuffers::Offset<Position>(fbb_.EndTable(start_, 5));
    return o;
  }
};

inline flatbuffers::Offset<Position> CreatePosition(flatbuffers::FlatBufferBuilder &_fbb,
    int32_t EntityID = 0,
    float StartTime = 0.0f,
    float EndTime = 0.0f,
    const FBS::Data::Vector3 *StartPos = 0,
    const FBS::Data::Vector3 *EndPos = 0) {
  PositionBuilder builder_(_fbb);
  builder_.add_EndPos(EndPos);
  builder_.add_StartPos(StartPos);
  builder_.add_EndTime(EndTime);
  builder_.add_StartTime(StartTime);
  builder_.add_EntityID(EntityID);
  return builder_.Finish();
}

}  // namespace GameEvent
}  // namespace FBS

#endif  // FLATBUFFERS_GENERATED_POSITION_FBS_GAMEEVENT_H_
