// automatically generated by the FlatBuffers compiler, do not modify

#ifndef FLATBUFFERS_GENERATED_GAMESTARTTOCDATA_H_
#define FLATBUFFERS_GENERATED_GAMESTARTTOCDATA_H_

#include "flatbuffers/flatbuffers.h"

struct GameStartToC_Data;

struct GameStartToC_Data FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           verifier.EndTable();
  }
};

struct GameStartToC_DataBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  GameStartToC_DataBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  GameStartToC_DataBuilder &operator=(const GameStartToC_DataBuilder &);
  flatbuffers::Offset<GameStartToC_Data> Finish() {
    auto o = flatbuffers::Offset<GameStartToC_Data>(fbb_.EndTable(start_, 0));
    return o;
  }
};

inline flatbuffers::Offset<GameStartToC_Data> CreateGameStartToC_Data(flatbuffers::FlatBufferBuilder &_fbb) {
  GameStartToC_DataBuilder builder_(_fbb);
  return builder_.Finish();
}

#endif  // FLATBUFFERS_GENERATED_GAMESTARTTOCDATA_H_
