// automatically generated by the FlatBuffers compiler, do not modify

#ifndef FLATBUFFERS_GENERATED_GAMEEVENTMOVETORDATA_H_
#define FLATBUFFERS_GENERATED_GAMEEVENTMOVETORDATA_H_

#include "flatbuffers\flatbuffers.h"

#include "FBSData_generated.h"

struct GameEventMoveToR_Data;

struct GameEventMoveToR_Data FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_PLAYERINDEX = 4,
    VT_DEST = 6
  };
  int32_t PlayerIndex() const { return GetField<int32_t>(VT_PLAYERINDEX, 0); }
  const FBSData::Vector3 *Dest() const { return GetStruct<const FBSData::Vector3 *>(VT_DEST); }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_PLAYERINDEX) &&
           VerifyField<FBSData::Vector3>(verifier, VT_DEST) &&
           verifier.EndTable();
  }
};

struct GameEventMoveToR_DataBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_PlayerIndex(int32_t PlayerIndex) { fbb_.AddElement<int32_t>(GameEventMoveToR_Data::VT_PLAYERINDEX, PlayerIndex, 0); }
  void add_Dest(const FBSData::Vector3 *Dest) { fbb_.AddStruct(GameEventMoveToR_Data::VT_DEST, Dest); }
  GameEventMoveToR_DataBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  GameEventMoveToR_DataBuilder &operator=(const GameEventMoveToR_DataBuilder &);
  flatbuffers::Offset<GameEventMoveToR_Data> Finish() {
    auto o = flatbuffers::Offset<GameEventMoveToR_Data>(fbb_.EndTable(start_, 2));
    return o;
  }
};

inline flatbuffers::Offset<GameEventMoveToR_Data> CreateGameEventMoveToR_Data(flatbuffers::FlatBufferBuilder &_fbb,
    int32_t PlayerIndex = 0,
    const FBSData::Vector3 *Dest = 0) {
  GameEventMoveToR_DataBuilder builder_(_fbb);
  builder_.add_Dest(Dest);
  builder_.add_PlayerIndex(PlayerIndex);
  return builder_.Finish();
}

#endif  // FLATBUFFERS_GENERATED_GAMEEVENTMOVETORDATA_H_
