// automatically generated by the FlatBuffers compiler, do not modify

#ifndef FLATBUFFERS_GENERATED_GAMEEVENTSTOPTOCDATA_H_
#define FLATBUFFERS_GENERATED_GAMEEVENTSTOPTOCDATA_H_

#include "flatbuffers/flatbuffers.h"

#include "FBSData_generated.h"

struct GameEventStopToC_Data;

struct GameEventStopToC_Data FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_PLAYERINDEX = 4,
    VT_EVENTTIME = 6,
    VT_POS = 8
  };
  int32_t PlayerIndex() const { return GetField<int32_t>(VT_PLAYERINDEX, 0); }
  int64_t EventTime() const { return GetField<int64_t>(VT_EVENTTIME, 0); }
  const FBSData::Vector3 *Pos() const { return GetStruct<const FBSData::Vector3 *>(VT_POS); }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_PLAYERINDEX) &&
           VerifyField<int64_t>(verifier, VT_EVENTTIME) &&
           VerifyField<FBSData::Vector3>(verifier, VT_POS) &&
           verifier.EndTable();
  }
};

struct GameEventStopToC_DataBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_PlayerIndex(int32_t PlayerIndex) { fbb_.AddElement<int32_t>(GameEventStopToC_Data::VT_PLAYERINDEX, PlayerIndex, 0); }
  void add_EventTime(int64_t EventTime) { fbb_.AddElement<int64_t>(GameEventStopToC_Data::VT_EVENTTIME, EventTime, 0); }
  void add_Pos(const FBSData::Vector3 *Pos) { fbb_.AddStruct(GameEventStopToC_Data::VT_POS, Pos); }
  GameEventStopToC_DataBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  GameEventStopToC_DataBuilder &operator=(const GameEventStopToC_DataBuilder &);
  flatbuffers::Offset<GameEventStopToC_Data> Finish() {
    auto o = flatbuffers::Offset<GameEventStopToC_Data>(fbb_.EndTable(start_, 3));
    return o;
  }
};

inline flatbuffers::Offset<GameEventStopToC_Data> CreateGameEventStopToC_Data(flatbuffers::FlatBufferBuilder &_fbb,
    int32_t PlayerIndex = 0,
    int64_t EventTime = 0,
    const FBSData::Vector3 *Pos = 0) {
  GameEventStopToC_DataBuilder builder_(_fbb);
  builder_.add_EventTime(EventTime);
  builder_.add_Pos(Pos);
  builder_.add_PlayerIndex(PlayerIndex);
  return builder_.Finish();
}

#endif  // FLATBUFFERS_GENERATED_GAMEEVENTSTOPTOCDATA_H_
