// automatically generated by the FlatBuffers compiler, do not modify

#ifndef FLATBUFFERS_GENERATED_GAMEEVENTMOVETOCDATA_H_
#define FLATBUFFERS_GENERATED_GAMEEVENTMOVETOCDATA_H_

#include "flatbuffers/flatbuffers.h"

#include "FBSData_generated.h"

struct GameEventMoveToC_Data;

struct GameEventMoveToC_Data FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_PLAYERINDEX = 4,
    VT_EVENTTIME = 6,
    VT_DEST = 8
  };
  int32_t PlayerIndex() const { return GetField<int32_t>(VT_PLAYERINDEX, 0); }
  int64_t EventTime() const { return GetField<int64_t>(VT_EVENTTIME, 0); }
  const FBSData::Vector3 *Dest() const { return GetStruct<const FBSData::Vector3 *>(VT_DEST); }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_PLAYERINDEX) &&
           VerifyField<int64_t>(verifier, VT_EVENTTIME) &&
           VerifyField<FBSData::Vector3>(verifier, VT_DEST) &&
           verifier.EndTable();
  }
};

struct GameEventMoveToC_DataBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_PlayerIndex(int32_t PlayerIndex) { fbb_.AddElement<int32_t>(GameEventMoveToC_Data::VT_PLAYERINDEX, PlayerIndex, 0); }
  void add_EventTime(int64_t EventTime) { fbb_.AddElement<int64_t>(GameEventMoveToC_Data::VT_EVENTTIME, EventTime, 0); }
  void add_Dest(const FBSData::Vector3 *Dest) { fbb_.AddStruct(GameEventMoveToC_Data::VT_DEST, Dest); }
  GameEventMoveToC_DataBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  GameEventMoveToC_DataBuilder &operator=(const GameEventMoveToC_DataBuilder &);
  flatbuffers::Offset<GameEventMoveToC_Data> Finish() {
    auto o = flatbuffers::Offset<GameEventMoveToC_Data>(fbb_.EndTable(start_, 3));
    return o;
  }
};

inline flatbuffers::Offset<GameEventMoveToC_Data> CreateGameEventMoveToC_Data(flatbuffers::FlatBufferBuilder &_fbb,
    int32_t PlayerIndex = 0,
    int64_t EventTime = 0,
    const FBSData::Vector3 *Dest = 0) {
  GameEventMoveToC_DataBuilder builder_(_fbb);
  builder_.add_EventTime(EventTime);
  builder_.add_Dest(Dest);
  builder_.add_PlayerIndex(PlayerIndex);
  return builder_.Finish();
}

#endif  // FLATBUFFERS_GENERATED_GAMEEVENTMOVETOCDATA_H_
