// automatically generated by the FlatBuffers compiler, do not modify

#ifndef FLATBUFFERS_GENERATED_GAMEEVENTTELEPORTTORDATA_H_
#define FLATBUFFERS_GENERATED_GAMEEVENTTELEPORTTORDATA_H_

#include "flatbuffers/flatbuffers.h"

#include "FBSData_generated.h"

struct GameEventTeleportToR_Data;

struct GameEventTeleportToR_Data FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_PLAYERINDEX = 4,
    VT_START = 6,
    VT_DEST = 8,
    VT_STATE = 10
  };
  int32_t PlayerIndex() const { return GetField<int32_t>(VT_PLAYERINDEX, 0); }
  const FBSData::Vector3 *Start() const { return GetStruct<const FBSData::Vector3 *>(VT_START); }
  const FBSData::Vector3 *Dest() const { return GetStruct<const FBSData::Vector3 *>(VT_DEST); }
  int32_t State() const { return GetField<int32_t>(VT_STATE, 0); }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_PLAYERINDEX) &&
           VerifyField<FBSData::Vector3>(verifier, VT_START) &&
           VerifyField<FBSData::Vector3>(verifier, VT_DEST) &&
           VerifyField<int32_t>(verifier, VT_STATE) &&
           verifier.EndTable();
  }
};

struct GameEventTeleportToR_DataBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_PlayerIndex(int32_t PlayerIndex) { fbb_.AddElement<int32_t>(GameEventTeleportToR_Data::VT_PLAYERINDEX, PlayerIndex, 0); }
  void add_Start(const FBSData::Vector3 *Start) { fbb_.AddStruct(GameEventTeleportToR_Data::VT_START, Start); }
  void add_Dest(const FBSData::Vector3 *Dest) { fbb_.AddStruct(GameEventTeleportToR_Data::VT_DEST, Dest); }
  void add_State(int32_t State) { fbb_.AddElement<int32_t>(GameEventTeleportToR_Data::VT_STATE, State, 0); }
  GameEventTeleportToR_DataBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  GameEventTeleportToR_DataBuilder &operator=(const GameEventTeleportToR_DataBuilder &);
  flatbuffers::Offset<GameEventTeleportToR_Data> Finish() {
    auto o = flatbuffers::Offset<GameEventTeleportToR_Data>(fbb_.EndTable(start_, 4));
    return o;
  }
};

inline flatbuffers::Offset<GameEventTeleportToR_Data> CreateGameEventTeleportToR_Data(flatbuffers::FlatBufferBuilder &_fbb,
    int32_t PlayerIndex = 0,
    const FBSData::Vector3 *Start = 0,
    const FBSData::Vector3 *Dest = 0,
    int32_t State = 0) {
  GameEventTeleportToR_DataBuilder builder_(_fbb);
  builder_.add_State(State);
  builder_.add_Dest(Dest);
  builder_.add_Start(Start);
  builder_.add_PlayerIndex(PlayerIndex);
  return builder_.Finish();
}

#endif  // FLATBUFFERS_GENERATED_GAMEEVENTTELEPORTTORDATA_H_
