// automatically generated by the FlatBuffers compiler, do not modify

#ifndef FLATBUFFERS_GENERATED_GAMEEVENTBEHAVIOREND_H_
#define FLATBUFFERS_GENERATED_GAMEEVENTBEHAVIOREND_H_

#include "flatbuffers/flatbuffers.h"

struct GameEvent_BehaviorEnd;

struct GameEvent_BehaviorEnd FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_ENTITYID = 4,
    VT_ENDTIME = 6,
    VT_BEHAVIORID = 8
  };
  int32_t EntityID() const { return GetField<int32_t>(VT_ENTITYID, 0); }
  float EndTime() const { return GetField<float>(VT_ENDTIME, 0.0f); }
  int32_t BehaviorID() const { return GetField<int32_t>(VT_BEHAVIORID, 0); }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_ENTITYID) &&
           VerifyField<float>(verifier, VT_ENDTIME) &&
           VerifyField<int32_t>(verifier, VT_BEHAVIORID) &&
           verifier.EndTable();
  }
};

struct GameEvent_BehaviorEndBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_EntityID(int32_t EntityID) { fbb_.AddElement<int32_t>(GameEvent_BehaviorEnd::VT_ENTITYID, EntityID, 0); }
  void add_EndTime(float EndTime) { fbb_.AddElement<float>(GameEvent_BehaviorEnd::VT_ENDTIME, EndTime, 0.0f); }
  void add_BehaviorID(int32_t BehaviorID) { fbb_.AddElement<int32_t>(GameEvent_BehaviorEnd::VT_BEHAVIORID, BehaviorID, 0); }
  GameEvent_BehaviorEndBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  GameEvent_BehaviorEndBuilder &operator=(const GameEvent_BehaviorEndBuilder &);
  flatbuffers::Offset<GameEvent_BehaviorEnd> Finish() {
    auto o = flatbuffers::Offset<GameEvent_BehaviorEnd>(fbb_.EndTable(start_, 3));
    return o;
  }
};

inline flatbuffers::Offset<GameEvent_BehaviorEnd> CreateGameEvent_BehaviorEnd(flatbuffers::FlatBufferBuilder &_fbb,
    int32_t EntityID = 0,
    float EndTime = 0.0f,
    int32_t BehaviorID = 0) {
  GameEvent_BehaviorEndBuilder builder_(_fbb);
  builder_.add_BehaviorID(BehaviorID);
  builder_.add_EndTime(EndTime);
  builder_.add_EntityID(EntityID);
  return builder_.Finish();
}

#endif  // FLATBUFFERS_GENERATED_GAMEEVENTBEHAVIOREND_H_
