// automatically generated by the FlatBuffers compiler, do not modify

#ifndef FLATBUFFERS_GENERATED_GAMEEVENTPOSITION_H_
#define FLATBUFFERS_GENERATED_GAMEEVENTPOSITION_H_

#include "flatbuffers/flatbuffers.h"

#include "FBSData_generated.h"

struct GameEvent_Position;

struct GameEvent_Position FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_ENTITYID = 4,
    VT_STARTTIME = 6,
    VT_ENDTIME = 8,
    VT_STARTPOSITION = 10,
    VT_ENDPOSITION = 12
  };
  int32_t EntityID() const { return GetField<int32_t>(VT_ENTITYID, 0); }
  float StartTime() const { return GetField<float>(VT_STARTTIME, 0.0f); }
  float EndTime() const { return GetField<float>(VT_ENDTIME, 0.0f); }
  const FBSData::Vector3 *StartPosition() const { return GetStruct<const FBSData::Vector3 *>(VT_STARTPOSITION); }
  const FBSData::Vector3 *EndPosition() const { return GetStruct<const FBSData::Vector3 *>(VT_ENDPOSITION); }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_ENTITYID) &&
           VerifyField<float>(verifier, VT_STARTTIME) &&
           VerifyField<float>(verifier, VT_ENDTIME) &&
           VerifyField<FBSData::Vector3>(verifier, VT_STARTPOSITION) &&
           VerifyField<FBSData::Vector3>(verifier, VT_ENDPOSITION) &&
           verifier.EndTable();
  }
};

struct GameEvent_PositionBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_EntityID(int32_t EntityID) { fbb_.AddElement<int32_t>(GameEvent_Position::VT_ENTITYID, EntityID, 0); }
  void add_StartTime(float StartTime) { fbb_.AddElement<float>(GameEvent_Position::VT_STARTTIME, StartTime, 0.0f); }
  void add_EndTime(float EndTime) { fbb_.AddElement<float>(GameEvent_Position::VT_ENDTIME, EndTime, 0.0f); }
  void add_StartPosition(const FBSData::Vector3 *StartPosition) { fbb_.AddStruct(GameEvent_Position::VT_STARTPOSITION, StartPosition); }
  void add_EndPosition(const FBSData::Vector3 *EndPosition) { fbb_.AddStruct(GameEvent_Position::VT_ENDPOSITION, EndPosition); }
  GameEvent_PositionBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  GameEvent_PositionBuilder &operator=(const GameEvent_PositionBuilder &);
  flatbuffers::Offset<GameEvent_Position> Finish() {
    auto o = flatbuffers::Offset<GameEvent_Position>(fbb_.EndTable(start_, 5));
    return o;
  }
};

inline flatbuffers::Offset<GameEvent_Position> CreateGameEvent_Position(flatbuffers::FlatBufferBuilder &_fbb,
    int32_t EntityID = 0,
    float StartTime = 0.0f,
    float EndTime = 0.0f,
    const FBSData::Vector3 *StartPosition = 0,
    const FBSData::Vector3 *EndPosition = 0) {
  GameEvent_PositionBuilder builder_(_fbb);
  builder_.add_EndPosition(EndPosition);
  builder_.add_StartPosition(StartPosition);
  builder_.add_EndTime(EndTime);
  builder_.add_StartTime(StartTime);
  builder_.add_EntityID(EntityID);
  return builder_.Finish();
}

#endif  // FLATBUFFERS_GENERATED_GAMEEVENTPOSITION_H_
