// automatically generated by the FlatBuffers compiler, do not modify

#ifndef FLATBUFFERS_GENERATED_GAMEEVENTIDLETORDATA_H_
#define FLATBUFFERS_GENERATED_GAMEEVENTIDLETORDATA_H_

#include "flatbuffers/flatbuffers.h"

#include "FBSData_generated.h"

struct GameEventIdleToR_Data;

struct GameEventIdleToR_Data FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_PLAYERINDEX = 4,
    VT_POS = 6
  };
  int32_t PlayerIndex() const { return GetField<int32_t>(VT_PLAYERINDEX, 0); }
  const FBSData::Vector3 *Pos() const { return GetStruct<const FBSData::Vector3 *>(VT_POS); }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_PLAYERINDEX) &&
           VerifyField<FBSData::Vector3>(verifier, VT_POS) &&
           verifier.EndTable();
  }
};

struct GameEventIdleToR_DataBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_PlayerIndex(int32_t PlayerIndex) { fbb_.AddElement<int32_t>(GameEventIdleToR_Data::VT_PLAYERINDEX, PlayerIndex, 0); }
  void add_Pos(const FBSData::Vector3 *Pos) { fbb_.AddStruct(GameEventIdleToR_Data::VT_POS, Pos); }
  GameEventIdleToR_DataBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  GameEventIdleToR_DataBuilder &operator=(const GameEventIdleToR_DataBuilder &);
  flatbuffers::Offset<GameEventIdleToR_Data> Finish() {
    auto o = flatbuffers::Offset<GameEventIdleToR_Data>(fbb_.EndTable(start_, 2));
    return o;
  }
};

inline flatbuffers::Offset<GameEventIdleToR_Data> CreateGameEventIdleToR_Data(flatbuffers::FlatBufferBuilder &_fbb,
    int32_t PlayerIndex = 0,
    const FBSData::Vector3 *Pos = 0) {
  GameEventIdleToR_DataBuilder builder_(_fbb);
  builder_.add_Pos(Pos);
  builder_.add_PlayerIndex(PlayerIndex);
  return builder_.Finish();
}

#endif  // FLATBUFFERS_GENERATED_GAMEEVENTIDLETORDATA_H_
