// automatically generated by the FlatBuffers compiler, do not modify

#ifndef FLATBUFFERS_GENERATED_GAMEEVENTSTATESTART_H_
#define FLATBUFFERS_GENERATED_GAMEEVENTSTATESTART_H_

#include "flatbuffers/flatbuffers.h"

struct GameEvent_StateStart;

struct GameEvent_StateStart FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_ENTITYID = 4,
    VT_STARTTIME = 6,
    VT_STATEID = 8
  };
  int32_t EntityID() const { return GetField<int32_t>(VT_ENTITYID, 0); }
  float StartTime() const { return GetField<float>(VT_STARTTIME, 0.0f); }
  int32_t StateID() const { return GetField<int32_t>(VT_STATEID, 0); }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_ENTITYID) &&
           VerifyField<float>(verifier, VT_STARTTIME) &&
           VerifyField<int32_t>(verifier, VT_STATEID) &&
           verifier.EndTable();
  }
};

struct GameEvent_StateStartBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_EntityID(int32_t EntityID) { fbb_.AddElement<int32_t>(GameEvent_StateStart::VT_ENTITYID, EntityID, 0); }
  void add_StartTime(float StartTime) { fbb_.AddElement<float>(GameEvent_StateStart::VT_STARTTIME, StartTime, 0.0f); }
  void add_StateID(int32_t StateID) { fbb_.AddElement<int32_t>(GameEvent_StateStart::VT_STATEID, StateID, 0); }
  GameEvent_StateStartBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  GameEvent_StateStartBuilder &operator=(const GameEvent_StateStartBuilder &);
  flatbuffers::Offset<GameEvent_StateStart> Finish() {
    auto o = flatbuffers::Offset<GameEvent_StateStart>(fbb_.EndTable(start_, 3));
    return o;
  }
};

inline flatbuffers::Offset<GameEvent_StateStart> CreateGameEvent_StateStart(flatbuffers::FlatBufferBuilder &_fbb,
    int32_t EntityID = 0,
    float StartTime = 0.0f,
    int32_t StateID = 0) {
  GameEvent_StateStartBuilder builder_(_fbb);
  builder_.add_StateID(StateID);
  builder_.add_StartTime(StartTime);
  builder_.add_EntityID(EntityID);
  return builder_.Finish();
}

#endif  // FLATBUFFERS_GENERATED_GAMEEVENTSTATESTART_H_
