// automatically generated by the FlatBuffers compiler, do not modify

#ifndef FLATBUFFERS_GENERATED_PREPARATIONSTATETORDATA_H_
#define FLATBUFFERS_GENERATED_PREPARATIONSTATETORDATA_H_

#include "flatbuffers/flatbuffers.h"

struct PreparationStateToR_Data;

struct PreparationStateToR_Data FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_STATE = 4
  };
  float State() const { return GetField<float>(VT_STATE, 0.0f); }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<float>(verifier, VT_STATE) &&
           verifier.EndTable();
  }
};

struct PreparationStateToR_DataBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_State(float State) { fbb_.AddElement<float>(PreparationStateToR_Data::VT_STATE, State, 0.0f); }
  PreparationStateToR_DataBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  PreparationStateToR_DataBuilder &operator=(const PreparationStateToR_DataBuilder &);
  flatbuffers::Offset<PreparationStateToR_Data> Finish() {
    auto o = flatbuffers::Offset<PreparationStateToR_Data>(fbb_.EndTable(start_, 1));
    return o;
  }
};

inline flatbuffers::Offset<PreparationStateToR_Data> CreatePreparationStateToR_Data(flatbuffers::FlatBufferBuilder &_fbb,
    float State = 0.0f) {
  PreparationStateToR_DataBuilder builder_(_fbb);
  builder_.add_State(State);
  return builder_.Finish();
}

#endif  // FLATBUFFERS_GENERATED_PREPARATIONSTATETORDATA_H_
