#pragma once

#include "Messages/GameEventMoveToC.h"
#include "Messages/GameEventMoveToR.h"
#include "Messages/GameStartToC.h"
#include "Messages/ReadyForStartToR.h"
#include "../CommonSources/Messages/CreateRoomToR.h"
#include "../CommonSources/Messages/CreateRoomToL.h"
#include "Messages/EnterRoomToC.h"
#include "Messages/EnterRoomToR.h"
#include "Messages\PlayerEnterRoomToC.h"
#include "Messages\PreparationStateToC.h"
#include "Messages\PreparationStateToR.h"
#include "Messages\GameEventIdleToC.h"
#include "Messages\GameEventIdleToR.h"
#include "Messages\GameEventStopToC.h"
#include "Messages\GameEventStopToR.h"