// automatically generated by the FlatBuffers compiler, do not modify

namespace FBS
{

using System;
using FlatBuffers;

public sealed class GameInputRotationToR : Table {
  public static GameInputRotationToR GetRootAsGameInputRotationToR(ByteBuffer _bb) { return GetRootAsGameInputRotationToR(_bb, new GameInputRotationToR()); }
  public static GameInputRotationToR GetRootAsGameInputRotationToR(ByteBuffer _bb, GameInputRotationToR obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public GameInputRotationToR __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public int PlayerIndex { get { int o = __offset(4); return o != 0 ? bb.GetInt(o + bb_pos) : (int)0; } }
  public FBS.Data.Vector3 Rotation { get { return GetRotation(new FBS.Data.Vector3()); } }
  public FBS.Data.Vector3 GetRotation(FBS.Data.Vector3 obj) { int o = __offset(6); return o != 0 ? obj.__init(o + bb_pos, bb) : null; }

  public static void StartGameInputRotationToR(FlatBufferBuilder builder) { builder.StartObject(2); }
  public static void AddPlayerIndex(FlatBufferBuilder builder, int PlayerIndex) { builder.AddInt(0, PlayerIndex, 0); }
  public static void AddRotation(FlatBufferBuilder builder, Offset<FBS.Data.Vector3> RotationOffset) { builder.AddStruct(1, RotationOffset.Value, 0); }
  public static Offset<GameInputRotationToR> EndGameInputRotationToR(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<GameInputRotationToR>(o);
  }
};


}
