// automatically generated by the FlatBuffers compiler, do not modify

namespace FBS
{

using System;
using FlatBuffers;

public sealed class GameEvent : Table {
  public static GameEvent GetRootAsGameEvent(ByteBuffer _bb) { return GetRootAsGameEvent(_bb, new GameEvent()); }
  public static GameEvent GetRootAsGameEvent(ByteBuffer _bb, GameEvent obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public GameEvent __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public GameEventType Type { get { int o = __offset(4); return o != 0 ? (GameEventType)bb.GetSbyte(o + bb_pos) : GameEventType.BehaviorStart; } }
  public sbyte GetData(int j) { int o = __offset(6); return o != 0 ? bb.GetSbyte(__vector(o) + j * 1) : (sbyte)0; }
  public int DataLength { get { int o = __offset(6); return o != 0 ? __vector_len(o) : 0; } }
  public ArraySegment<byte>? GetDataBytes() { return __vector_as_arraysegment(6); }

  public static Offset<GameEvent> CreateGameEvent(FlatBufferBuilder builder,
      GameEventType Type = GameEventType.BehaviorStart,
      VectorOffset DataOffset = default(VectorOffset)) {
    builder.StartObject(2);
    GameEvent.AddData(builder, DataOffset);
    GameEvent.AddType(builder, Type);
    return GameEvent.EndGameEvent(builder);
  }

  public static void StartGameEvent(FlatBufferBuilder builder) { builder.StartObject(2); }
  public static void AddType(FlatBufferBuilder builder, GameEventType Type) { builder.AddSbyte(0, (sbyte)Type, 0); }
  public static void AddData(FlatBufferBuilder builder, VectorOffset DataOffset) { builder.AddOffset(1, DataOffset.Value, 0); }
  public static VectorOffset CreateDataVector(FlatBufferBuilder builder, sbyte[] data) { builder.StartVector(1, data.Length, 1); for (int i = data.Length - 1; i >= 0; i--) builder.AddSbyte(data[i]); return builder.EndVector(); }
  public static void StartDataVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(1, numElems, 1); }
  public static Offset<GameEvent> EndGameEvent(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<GameEvent>(o);
  }
};


}
