// automatically generated by the FlatBuffers compiler, do not modify

namespace FBS
{

using System;
using FlatBuffers;

public sealed class GameEventData : Table {
  public static GameEventData GetRootAsGameEventData(ByteBuffer _bb) { return GetRootAsGameEventData(_bb, new GameEventData()); }
  public static GameEventData GetRootAsGameEventData(ByteBuffer _bb, GameEventData obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public GameEventData __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public GameEventType Type { get { int o = __offset(4); return o != 0 ? (GameEventType)bb.GetSbyte(o + bb_pos) : GameEventType.BehaviorStart; } }
  public float EventTime { get { int o = __offset(6); return o != 0 ? bb.GetFloat(o + bb_pos) : (float)0.0f; } }
  public sbyte GetData(int j) { int o = __offset(8); return o != 0 ? bb.GetSbyte(__vector(o) + j * 1) : (sbyte)0; }
  public int DataLength { get { int o = __offset(8); return o != 0 ? __vector_len(o) : 0; } }
  public ArraySegment<byte>? GetDataBytes() { return __vector_as_arraysegment(8); }

  public static Offset<GameEventData> CreateGameEventData(FlatBufferBuilder builder,
      GameEventType Type = GameEventType.BehaviorStart,
      float EventTime = 0.0f,
      VectorOffset DataOffset = default(VectorOffset)) {
    builder.StartObject(3);
    GameEventData.AddData(builder, DataOffset);
    GameEventData.AddEventTime(builder, EventTime);
    GameEventData.AddType(builder, Type);
    return GameEventData.EndGameEventData(builder);
  }

  public static void StartGameEventData(FlatBufferBuilder builder) { builder.StartObject(3); }
  public static void AddType(FlatBufferBuilder builder, GameEventType Type) { builder.AddSbyte(0, (sbyte)Type, 0); }
  public static void AddEventTime(FlatBufferBuilder builder, float EventTime) { builder.AddFloat(1, EventTime, 0.0f); }
  public static void AddData(FlatBufferBuilder builder, VectorOffset DataOffset) { builder.AddOffset(2, DataOffset.Value, 0); }
  public static VectorOffset CreateDataVector(FlatBufferBuilder builder, sbyte[] data) { builder.StartVector(1, data.Length, 1); for (int i = data.Length - 1; i >= 0; i--) builder.AddSbyte(data[i]); return builder.EndVector(); }
  public static void StartDataVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(1, numElems, 1); }
  public static Offset<GameEventData> EndGameEventData(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<GameEventData>(o);
  }
};


}
