// automatically generated by the FlatBuffers compiler, do not modify

namespace FBS
{

using System;
using FlatBuffers;

public sealed class PlayerInfo : Struct {
  public PlayerInfo __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public int PlayerIndex { get { return bb.GetInt(bb_pos + 0); } }
  public int MasterDataID { get { return bb.GetInt(bb_pos + 4); } }
  public int EntityID { get { return bb.GetInt(bb_pos + 8); } }

  public static Offset<PlayerInfo> CreatePlayerInfo(FlatBufferBuilder builder, int PlayerIndex, int MasterDataID, int EntityID) {
    builder.Prep(4, 12);
    builder.PutInt(EntityID);
    builder.PutInt(MasterDataID);
    builder.PutInt(PlayerIndex);
    return new Offset<PlayerInfo>(builder.Offset);
  }
};


}
