// automatically generated by the FlatBuffers compiler, do not modify

using System;
using FlatBuffers;

public sealed class GameEventMoveToC_Data : Table {
  public static GameEventMoveToC_Data GetRootAsGameEventMoveToC_Data(ByteBuffer _bb) { return GetRootAsGameEventMoveToC_Data(_bb, new GameEventMoveToC_Data()); }
  public static GameEventMoveToC_Data GetRootAsGameEventMoveToC_Data(ByteBuffer _bb, GameEventMoveToC_Data obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public GameEventMoveToC_Data __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public int PlayerIndex { get { int o = __offset(4); return o != 0 ? bb.GetInt(o + bb_pos) : (int)0; } }
  public long EventTime { get { int o = __offset(6); return o != 0 ? bb.GetLong(o + bb_pos) : (long)0; } }
  public FBSData.Vector3 Dest { get { return GetDest(new FBSData.Vector3()); } }
  public FBSData.Vector3 GetDest(FBSData.Vector3 obj) { int o = __offset(8); return o != 0 ? obj.__init(o + bb_pos, bb) : null; }

  public static void StartGameEventMoveToC_Data(FlatBufferBuilder builder) { builder.StartObject(3); }
  public static void AddPlayerIndex(FlatBufferBuilder builder, int PlayerIndex) { builder.AddInt(0, PlayerIndex, 0); }
  public static void AddEventTime(FlatBufferBuilder builder, long EventTime) { builder.AddLong(1, EventTime, 0); }
  public static void AddDest(FlatBufferBuilder builder, Offset<FBSData.Vector3> DestOffset) { builder.AddStruct(2, DestOffset.Value, 0); }
  public static Offset<GameEventMoveToC_Data> EndGameEventMoveToC_Data(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<GameEventMoveToC_Data>(o);
  }
};

