// automatically generated by the FlatBuffers compiler, do not modify

using System;
using FlatBuffers;

public sealed class PreparationStateToC_Data : Table {
  public static PreparationStateToC_Data GetRootAsPreparationStateToC_Data(ByteBuffer _bb) { return GetRootAsPreparationStateToC_Data(_bb, new PreparationStateToC_Data()); }
  public static PreparationStateToC_Data GetRootAsPreparationStateToC_Data(ByteBuffer _bb, PreparationStateToC_Data obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public PreparationStateToC_Data __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public int PlayerIndex { get { int o = __offset(4); return o != 0 ? bb.GetInt(o + bb_pos) : (int)0; } }
  public float State { get { int o = __offset(6); return o != 0 ? bb.GetFloat(o + bb_pos) : (float)0.0f; } }

  public static Offset<PreparationStateToC_Data> CreatePreparationStateToC_Data(FlatBufferBuilder builder,
      int PlayerIndex = 0,
      float State = 0.0f) {
    builder.StartObject(2);
    PreparationStateToC_Data.AddState(builder, State);
    PreparationStateToC_Data.AddPlayerIndex(builder, PlayerIndex);
    return PreparationStateToC_Data.EndPreparationStateToC_Data(builder);
  }

  public static void StartPreparationStateToC_Data(FlatBufferBuilder builder) { builder.StartObject(2); }
  public static void AddPlayerIndex(FlatBufferBuilder builder, int PlayerIndex) { builder.AddInt(0, PlayerIndex, 0); }
  public static void AddState(FlatBufferBuilder builder, float State) { builder.AddFloat(1, State, 0.0f); }
  public static Offset<PreparationStateToC_Data> EndPreparationStateToC_Data(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<PreparationStateToC_Data>(o);
  }
};

