// automatically generated by the FlatBuffers compiler, do not modify

#ifndef FLATBUFFERS_GENERATED_ROTATION_FBS_GAMEEVENT_H_
#define FLATBUFFERS_GENERATED_ROTATION_FBS_GAMEEVENT_H_

#include "flatbuffers/flatbuffers.h"

#include "FBSData_generated.h"

namespace FBS {
namespace GameEvent {

struct Rotation;

struct Rotation FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_ENTITYID = 4,
    VT_STARTTIME = 6,
    VT_ENDTIME = 8,
    VT_STARTROT = 10,
    VT_ENDROT = 12
  };
  int32_t EntityID() const { return GetField<int32_t>(VT_ENTITYID, 0); }
  float StartTime() const { return GetField<float>(VT_STARTTIME, 0.0f); }
  float EndTime() const { return GetField<float>(VT_ENDTIME, 0.0f); }
  const FBSData::Vector3 *StartRot() const { return GetStruct<const FBSData::Vector3 *>(VT_STARTROT); }
  const FBSData::Vector3 *EndRot() const { return GetStruct<const FBSData::Vector3 *>(VT_ENDROT); }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_ENTITYID) &&
           VerifyField<float>(verifier, VT_STARTTIME) &&
           VerifyField<float>(verifier, VT_ENDTIME) &&
           VerifyField<FBSData::Vector3>(verifier, VT_STARTROT) &&
           VerifyField<FBSData::Vector3>(verifier, VT_ENDROT) &&
           verifier.EndTable();
  }
};

struct RotationBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_EntityID(int32_t EntityID) { fbb_.AddElement<int32_t>(Rotation::VT_ENTITYID, EntityID, 0); }
  void add_StartTime(float StartTime) { fbb_.AddElement<float>(Rotation::VT_STARTTIME, StartTime, 0.0f); }
  void add_EndTime(float EndTime) { fbb_.AddElement<float>(Rotation::VT_ENDTIME, EndTime, 0.0f); }
  void add_StartRot(const FBSData::Vector3 *StartRot) { fbb_.AddStruct(Rotation::VT_STARTROT, StartRot); }
  void add_EndRot(const FBSData::Vector3 *EndRot) { fbb_.AddStruct(Rotation::VT_ENDROT, EndRot); }
  RotationBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  RotationBuilder &operator=(const RotationBuilder &);
  flatbuffers::Offset<Rotation> Finish() {
    auto o = flatbuffers::Offset<Rotation>(fbb_.EndTable(start_, 5));
    return o;
  }
};

inline flatbuffers::Offset<Rotation> CreateRotation(flatbuffers::FlatBufferBuilder &_fbb,
    int32_t EntityID = 0,
    float StartTime = 0.0f,
    float EndTime = 0.0f,
    const FBSData::Vector3 *StartRot = 0,
    const FBSData::Vector3 *EndRot = 0) {
  RotationBuilder builder_(_fbb);
  builder_.add_EndRot(EndRot);
  builder_.add_StartRot(StartRot);
  builder_.add_EndTime(EndTime);
  builder_.add_StartTime(StartTime);
  builder_.add_EntityID(EntityID);
  return builder_.Finish();
}

}  // namespace GameEvent
}  // namespace FBS

#endif  // FLATBUFFERS_GENERATED_ROTATION_FBS_GAMEEVENT_H_
