// automatically generated by the FlatBuffers compiler, do not modify

namespace FBS.GameEvent
{

using System;
using FlatBuffers;

public sealed class BehaviorStart : Table {
  public static BehaviorStart GetRootAsBehaviorStart(ByteBuffer _bb) { return GetRootAsBehaviorStart(_bb, new BehaviorStart()); }
  public static BehaviorStart GetRootAsBehaviorStart(ByteBuffer _bb, BehaviorStart obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public BehaviorStart __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public int EntityID { get { int o = __offset(4); return o != 0 ? bb.GetInt(o + bb_pos) : (int)0; } }
  public float StartTime { get { int o = __offset(6); return o != 0 ? bb.GetFloat(o + bb_pos) : (float)0.0f; } }
  public int BehaviorID { get { int o = __offset(8); return o != 0 ? bb.GetInt(o + bb_pos) : (int)0; } }

  public static Offset<BehaviorStart> CreateBehaviorStart(FlatBufferBuilder builder,
      int EntityID = 0,
      float StartTime = 0.0f,
      int BehaviorID = 0) {
    builder.StartObject(3);
    BehaviorStart.AddBehaviorID(builder, BehaviorID);
    BehaviorStart.AddStartTime(builder, StartTime);
    BehaviorStart.AddEntityID(builder, EntityID);
    return BehaviorStart.EndBehaviorStart(builder);
  }

  public static void StartBehaviorStart(FlatBufferBuilder builder) { builder.StartObject(3); }
  public static void AddEntityID(FlatBufferBuilder builder, int EntityID) { builder.AddInt(0, EntityID, 0); }
  public static void AddStartTime(FlatBufferBuilder builder, float StartTime) { builder.AddFloat(1, StartTime, 0.0f); }
  public static void AddBehaviorID(FlatBufferBuilder builder, int BehaviorID) { builder.AddInt(2, BehaviorID, 0); }
  public static Offset<BehaviorStart> EndBehaviorStart(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<BehaviorStart>(o);
  }
};


}
