// automatically generated by the FlatBuffers compiler, do not modify

namespace FBS.GameEvent
{

using System;
using FlatBuffers;

public sealed class CharacterStatusChange : Table {
  public static CharacterStatusChange GetRootAsCharacterStatusChange(ByteBuffer _bb) { return GetRootAsCharacterStatusChange(_bb, new CharacterStatusChange()); }
  public static CharacterStatusChange GetRootAsCharacterStatusChange(ByteBuffer _bb, CharacterStatusChange obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public CharacterStatusChange __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public int EntityID { get { int o = __offset(4); return o != 0 ? bb.GetInt(o + bb_pos) : (int)0; } }
  public string StatusField { get { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; } }
  public ArraySegment<byte>? GetStatusFieldBytes() { return __vector_as_arraysegment(6); }
  public string Reason { get { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; } }
  public ArraySegment<byte>? GetReasonBytes() { return __vector_as_arraysegment(8); }
  public float Value { get { int o = __offset(10); return o != 0 ? bb.GetFloat(o + bb_pos) : (float)0.0f; } }

  public static Offset<CharacterStatusChange> CreateCharacterStatusChange(FlatBufferBuilder builder,
      int EntityID = 0,
      StringOffset StatusFieldOffset = default(StringOffset),
      StringOffset ReasonOffset = default(StringOffset),
      float Value = 0.0f) {
    builder.StartObject(4);
    CharacterStatusChange.AddValue(builder, Value);
    CharacterStatusChange.AddReason(builder, ReasonOffset);
    CharacterStatusChange.AddStatusField(builder, StatusFieldOffset);
    CharacterStatusChange.AddEntityID(builder, EntityID);
    return CharacterStatusChange.EndCharacterStatusChange(builder);
  }

  public static void StartCharacterStatusChange(FlatBufferBuilder builder) { builder.StartObject(4); }
  public static void AddEntityID(FlatBufferBuilder builder, int EntityID) { builder.AddInt(0, EntityID, 0); }
  public static void AddStatusField(FlatBufferBuilder builder, StringOffset StatusFieldOffset) { builder.AddOffset(1, StatusFieldOffset.Value, 0); }
  public static void AddReason(FlatBufferBuilder builder, StringOffset ReasonOffset) { builder.AddOffset(2, ReasonOffset.Value, 0); }
  public static void AddValue(FlatBufferBuilder builder, float Value) { builder.AddFloat(3, Value, 0.0f); }
  public static Offset<CharacterStatusChange> EndCharacterStatusChange(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<CharacterStatusChange>(o);
  }
};


}
