// automatically generated by the FlatBuffers compiler, do not modify

namespace FBS.GameEvent
{

using System;
using FlatBuffers;

public sealed class StateStart : Table {
  public static StateStart GetRootAsStateStart(ByteBuffer _bb) { return GetRootAsStateStart(_bb, new StateStart()); }
  public static StateStart GetRootAsStateStart(ByteBuffer _bb, StateStart obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public StateStart __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public int EntityID { get { int o = __offset(4); return o != 0 ? bb.GetInt(o + bb_pos) : (int)0; } }
  public float StartTime { get { int o = __offset(6); return o != 0 ? bb.GetFloat(o + bb_pos) : (float)0.0f; } }
  public int StateID { get { int o = __offset(8); return o != 0 ? bb.GetInt(o + bb_pos) : (int)0; } }

  public static Offset<StateStart> CreateStateStart(FlatBufferBuilder builder,
      int EntityID = 0,
      float StartTime = 0.0f,
      int StateID = 0) {
    builder.StartObject(3);
    StateStart.AddStateID(builder, StateID);
    StateStart.AddStartTime(builder, StartTime);
    StateStart.AddEntityID(builder, EntityID);
    return StateStart.EndStateStart(builder);
  }

  public static void StartStateStart(FlatBufferBuilder builder) { builder.StartObject(3); }
  public static void AddEntityID(FlatBufferBuilder builder, int EntityID) { builder.AddInt(0, EntityID, 0); }
  public static void AddStartTime(FlatBufferBuilder builder, float StartTime) { builder.AddFloat(1, StartTime, 0.0f); }
  public static void AddStateID(FlatBufferBuilder builder, int StateID) { builder.AddInt(2, StateID, 0); }
  public static Offset<StateStart> EndStateStart(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<StateStart>(o);
  }
};


}
