// automatically generated by the FlatBuffers compiler, do not modify

using System;
using FlatBuffers;

public sealed class EnterRoomToR_Data : Table {
  public static EnterRoomToR_Data GetRootAsEnterRoomToR_Data(ByteBuffer _bb) { return GetRootAsEnterRoomToR_Data(_bb, new EnterRoomToR_Data()); }
  public static EnterRoomToR_Data GetRootAsEnterRoomToR_Data(ByteBuffer _bb, EnterRoomToR_Data obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public EnterRoomToR_Data __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public string PlayerKey { get { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; } }
  public ArraySegment<byte>? GetPlayerKeyBytes() { return __vector_as_arraysegment(4); }
  public int AuthKey { get { int o = __offset(6); return o != 0 ? bb.GetInt(o + bb_pos) : (int)0; } }
  public int MatchID { get { int o = __offset(8); return o != 0 ? bb.GetInt(o + bb_pos) : (int)0; } }

  public static Offset<EnterRoomToR_Data> CreateEnterRoomToR_Data(FlatBufferBuilder builder,
      StringOffset PlayerKeyOffset = default(StringOffset),
      int AuthKey = 0,
      int MatchID = 0) {
    builder.StartObject(3);
    EnterRoomToR_Data.AddMatchID(builder, MatchID);
    EnterRoomToR_Data.AddAuthKey(builder, AuthKey);
    EnterRoomToR_Data.AddPlayerKey(builder, PlayerKeyOffset);
    return EnterRoomToR_Data.EndEnterRoomToR_Data(builder);
  }

  public static void StartEnterRoomToR_Data(FlatBufferBuilder builder) { builder.StartObject(3); }
  public static void AddPlayerKey(FlatBufferBuilder builder, StringOffset PlayerKeyOffset) { builder.AddOffset(0, PlayerKeyOffset.Value, 0); }
  public static void AddAuthKey(FlatBufferBuilder builder, int AuthKey) { builder.AddInt(1, AuthKey, 0); }
  public static void AddMatchID(FlatBufferBuilder builder, int MatchID) { builder.AddInt(2, MatchID, 0); }
  public static Offset<EnterRoomToR_Data> EndEnterRoomToR_Data(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<EnterRoomToR_Data>(o);
  }
};

