// automatically generated by the FlatBuffers compiler, do not modify

using System;
using FlatBuffers;

public sealed class GameEventMoveToR_Data : Table {
  public static GameEventMoveToR_Data GetRootAsGameEventMoveToR_Data(ByteBuffer _bb) { return GetRootAsGameEventMoveToR_Data(_bb, new GameEventMoveToR_Data()); }
  public static GameEventMoveToR_Data GetRootAsGameEventMoveToR_Data(ByteBuffer _bb, GameEventMoveToR_Data obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public GameEventMoveToR_Data __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public int PlayerIndex { get { int o = __offset(4); return o != 0 ? bb.GetInt(o + bb_pos) : (int)0; } }
  public FBSData.Vector3 Dest { get { return GetDest(new FBSData.Vector3()); } }
  public FBSData.Vector3 GetDest(FBSData.Vector3 obj) { int o = __offset(6); return o != 0 ? obj.__init(o + bb_pos, bb) : null; }

  public static void StartGameEventMoveToR_Data(FlatBufferBuilder builder) { builder.StartObject(2); }
  public static void AddPlayerIndex(FlatBufferBuilder builder, int PlayerIndex) { builder.AddInt(0, PlayerIndex, 0); }
  public static void AddDest(FlatBufferBuilder builder, Offset<FBSData.Vector3> DestOffset) { builder.AddStruct(1, DestOffset.Value, 0); }
  public static Offset<GameEventMoveToR_Data> EndGameEventMoveToR_Data(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<GameEventMoveToR_Data>(o);
  }
};

