// automatically generated by the FlatBuffers compiler, do not modify

using System;
using FlatBuffers;

public sealed class GameEventTeleportToR_Data : Table {
  public static GameEventTeleportToR_Data GetRootAsGameEventTeleportToR_Data(ByteBuffer _bb) { return GetRootAsGameEventTeleportToR_Data(_bb, new GameEventTeleportToR_Data()); }
  public static GameEventTeleportToR_Data GetRootAsGameEventTeleportToR_Data(ByteBuffer _bb, GameEventTeleportToR_Data obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public GameEventTeleportToR_Data __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public int PlayerIndex { get { int o = __offset(4); return o != 0 ? bb.GetInt(o + bb_pos) : (int)0; } }
  public FBSData.Vector3 Start { get { return GetStart(new FBSData.Vector3()); } }
  public FBSData.Vector3 GetStart(FBSData.Vector3 obj) { int o = __offset(6); return o != 0 ? obj.__init(o + bb_pos, bb) : null; }
  public FBSData.Vector3 Dest { get { return GetDest(new FBSData.Vector3()); } }
  public FBSData.Vector3 GetDest(FBSData.Vector3 obj) { int o = __offset(8); return o != 0 ? obj.__init(o + bb_pos, bb) : null; }
  public int State { get { int o = __offset(10); return o != 0 ? bb.GetInt(o + bb_pos) : (int)0; } }

  public static void StartGameEventTeleportToR_Data(FlatBufferBuilder builder) { builder.StartObject(4); }
  public static void AddPlayerIndex(FlatBufferBuilder builder, int PlayerIndex) { builder.AddInt(0, PlayerIndex, 0); }
  public static void AddStart(FlatBufferBuilder builder, Offset<FBSData.Vector3> StartOffset) { builder.AddStruct(1, StartOffset.Value, 0); }
  public static void AddDest(FlatBufferBuilder builder, Offset<FBSData.Vector3> DestOffset) { builder.AddStruct(2, DestOffset.Value, 0); }
  public static void AddState(FlatBufferBuilder builder, int State) { builder.AddInt(3, State, 0); }
  public static Offset<GameEventTeleportToR_Data> EndGameEventTeleportToR_Data(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<GameEventTeleportToR_Data>(o);
  }
};

