// automatically generated by the FlatBuffers compiler, do not modify

using System;
using FlatBuffers;

public sealed class PreparationStateToR_Data : Table {
  public static PreparationStateToR_Data GetRootAsPreparationStateToR_Data(ByteBuffer _bb) { return GetRootAsPreparationStateToR_Data(_bb, new PreparationStateToR_Data()); }
  public static PreparationStateToR_Data GetRootAsPreparationStateToR_Data(ByteBuffer _bb, PreparationStateToR_Data obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public PreparationStateToR_Data __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public float State { get { int o = __offset(4); return o != 0 ? bb.GetFloat(o + bb_pos) : (float)0.0f; } }

  public static Offset<PreparationStateToR_Data> CreatePreparationStateToR_Data(FlatBufferBuilder builder,
      float State = 0.0f) {
    builder.StartObject(1);
    PreparationStateToR_Data.AddState(builder, State);
    return PreparationStateToR_Data.EndPreparationStateToR_Data(builder);
  }

  public static void StartPreparationStateToR_Data(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddState(FlatBufferBuilder builder, float State) { builder.AddFloat(0, State, 0.0f); }
  public static Offset<PreparationStateToR_Data> EndPreparationStateToR_Data(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<PreparationStateToR_Data>(o);
  }
};

