// automatically generated by the FlatBuffers compiler, do not modify

using System;
using FlatBuffers;

public sealed class ReadyForStartToR_Data : Table {
  public static ReadyForStartToR_Data GetRootAsReadyForStartToR_Data(ByteBuffer _bb) { return GetRootAsReadyForStartToR_Data(_bb, new ReadyForStartToR_Data()); }
  public static ReadyForStartToR_Data GetRootAsReadyForStartToR_Data(ByteBuffer _bb, ReadyForStartToR_Data obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public ReadyForStartToR_Data __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public int PlayerIndex { get { int o = __offset(4); return o != 0 ? bb.GetInt(o + bb_pos) : (int)0; } }

  public static Offset<ReadyForStartToR_Data> CreateReadyForStartToR_Data(FlatBufferBuilder builder,
      int PlayerIndex = 0) {
    builder.StartObject(1);
    ReadyForStartToR_Data.AddPlayerIndex(builder, PlayerIndex);
    return ReadyForStartToR_Data.EndReadyForStartToR_Data(builder);
  }

  public static void StartReadyForStartToR_Data(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddPlayerIndex(FlatBufferBuilder builder, int PlayerIndex) { builder.AddInt(0, PlayerIndex, 0); }
  public static Offset<ReadyForStartToR_Data> EndReadyForStartToR_Data(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<ReadyForStartToR_Data>(o);
  }
};

