// automatically generated by the FlatBuffers compiler, do not modify

namespace FBS.GameEvent
{

using System;
using FlatBuffers;

public sealed class EntityDestroy : Table {
  public static EntityDestroy GetRootAsEntityDestroy(ByteBuffer _bb) { return GetRootAsEntityDestroy(_bb, new EntityDestroy()); }
  public static EntityDestroy GetRootAsEntityDestroy(ByteBuffer _bb, EntityDestroy obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public EntityDestroy __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public int EntityID { get { int o = __offset(4); return o != 0 ? bb.GetInt(o + bb_pos) : (int)0; } }

  public static Offset<EntityDestroy> CreateEntityDestroy(FlatBufferBuilder builder,
      int EntityID = 0) {
    builder.StartObject(1);
    EntityDestroy.AddEntityID(builder, EntityID);
    return EntityDestroy.EndEntityDestroy(builder);
  }

  public static void StartEntityDestroy(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddEntityID(FlatBufferBuilder builder, int EntityID) { builder.AddInt(0, EntityID, 0); }
  public static Offset<EntityDestroy> EndEntityDestroy(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<EntityDestroy>(o);
  }
};


}
