// automatically generated by the FlatBuffers compiler, do not modify

namespace FBS.GameEvent
{

using System;
using FlatBuffers;

public sealed class StateEnd : Table {
  public static StateEnd GetRootAsStateEnd(ByteBuffer _bb) { return GetRootAsStateEnd(_bb, new StateEnd()); }
  public static StateEnd GetRootAsStateEnd(ByteBuffer _bb, StateEnd obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public StateEnd __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public int EntityID { get { int o = __offset(4); return o != 0 ? bb.GetInt(o + bb_pos) : (int)0; } }
  public float EndTime { get { int o = __offset(6); return o != 0 ? bb.GetFloat(o + bb_pos) : (float)0.0f; } }
  public int StateID { get { int o = __offset(8); return o != 0 ? bb.GetInt(o + bb_pos) : (int)0; } }

  public static Offset<StateEnd> CreateStateEnd(FlatBufferBuilder builder,
      int EntityID = 0,
      float EndTime = 0.0f,
      int StateID = 0) {
    builder.StartObject(3);
    StateEnd.AddStateID(builder, StateID);
    StateEnd.AddEndTime(builder, EndTime);
    StateEnd.AddEntityID(builder, EntityID);
    return StateEnd.EndStateEnd(builder);
  }

  public static void StartStateEnd(FlatBufferBuilder builder) { builder.StartObject(3); }
  public static void AddEntityID(FlatBufferBuilder builder, int EntityID) { builder.AddInt(0, EntityID, 0); }
  public static void AddEndTime(FlatBufferBuilder builder, float EndTime) { builder.AddFloat(1, EndTime, 0.0f); }
  public static void AddStateID(FlatBufferBuilder builder, int StateID) { builder.AddInt(2, StateID, 0); }
  public static Offset<StateEnd> EndStateEnd(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<StateEnd>(o);
  }
};


}
